package api

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"golang.org/x/crypto/bcrypt"
)

type adminAccount struct { ID, Username, Role string }

// registerAdminRoutes is deliberately limited to the Node admin operations
// migrated in this stage.  The legacy catch-all retains JSON 501 responses for
// the remaining admin families until their own migration is authorized.
func (s *Server) registerAdminRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/admin/login", s.adminLogin)
	mux.HandleFunc("POST /api/admin/logout", s.requireAdmin(s.adminLogout))
	mux.HandleFunc("GET /api/admin/me", s.requireAdmin(s.adminMe))
	mux.HandleFunc("GET /api/admin/dashboard", s.requireAdmin(s.adminDashboard))
	mux.HandleFunc("GET /api/admin/users", s.requireAdmin(s.adminUsers))
	mux.HandleFunc("GET /api/admin/users/{id}", s.requireAdmin(s.adminUser))
	mux.HandleFunc("POST /api/admin/users/{id}/ban", s.requireAdmin(s.adminBanUser))
	mux.HandleFunc("GET /api/admin/logs", s.requireAdmin(s.adminLogs))
}

func adminToken(r *http.Request) string {
	if token:=bearerToken(r.Header.Get("Authorization"));token!="" { return token }
	if cookie,err:=r.Cookie("admin_token");err==nil { return cookie.Value }
	return ""
}

func (s *Server) findAdmin(ctx context.Context, token string) (adminAccount,error) {
	var a adminAccount
	err:=s.db.QueryRow(ctx,`SELECT a."id",a."username",a."role" FROM "AdminSession" s JOIN "AdminAccount" a ON a."id"=s."adminId" WHERE s."token"=$1 AND s."expiresAt">NOW() LIMIT 1`,token).Scan(&a.ID,&a.Username,&a.Role)
	return a,err
}

func (s *Server) requireAdmin(next func(http.ResponseWriter,*http.Request,adminAccount,string)) http.HandlerFunc {
	return func(w http.ResponseWriter,r *http.Request){token:=adminToken(r);if token==""{writeJSON(w,401,map[string]string{"error":"未登录"});return};a,e:=s.findAdmin(r.Context(),token);if e==pgx.ErrNoRows{_,_=s.db.Exec(r.Context(),`DELETE FROM "AdminSession" WHERE "token"=$1`,token);writeJSON(w,401,map[string]string{"error":"登录已过期"});return};if e!=nil{writeJSON(w,503,map[string]string{"error":"认证服务不可用"});return};next(w,r,a,token)}
}

func adminAllowed(a adminAccount) bool { return a.Role=="superadmin"||a.Role=="admin" }
func adminClientIP(r *http.Request) string { if raw:=r.Header.Get("X-Forwarded-For");raw!="" {return strings.TrimSpace(strings.Split(raw,",")[0])};return r.RemoteAddr }
func adminNewToken() string { b:=make([]byte,36);if _,e:=rand.Read(b);e!=nil{return newID()+newID()};return base64.RawURLEncoding.EncodeToString(b)[:48] }
func adminLegacyHash(password string) string { h:=sha256.Sum256([]byte(password+"cqim_salt_2024"));return hex.EncodeToString(h[:]) }
func adminVerify(password, hash string) bool { if strings.HasPrefix(hash,"$2a$")||strings.HasPrefix(hash,"$2b$")||strings.HasPrefix(hash,"$2y$"){return bcrypt.CompareHashAndPassword([]byte(hash),[]byte(password))==nil};return len(hash)==64&&adminLegacyHash(password)==hash }
func (s *Server) adminAddLog(ctx context.Context,a *adminAccount,action,target,detail,ip string){var id,name *string;if a!=nil{id=&a.ID;name=&a.Username};_,_=s.db.Exec(ctx,`INSERT INTO "AdminLog" ("id","adminId","adminName","action","target","detail","ip","createdAt") VALUES ($1,$2,$3,$4,NULLIF($5,''),NULLIF($6,''),NULLIF($7,''),NOW())`,newID(),id,name,action,target,detail,ip)}

func (s *Server) adminLogin(w http.ResponseWriter,r *http.Request){var in struct{Username,Password string};if decode(r,&in)!=nil||in.Username==""||in.Password==""{writeJSON(w,400,map[string]string{"error":"请填写用户名和密码"});return};var a adminAccount;var hash string;e:=s.db.QueryRow(r.Context(),`SELECT "id","username","role","password" FROM "AdminAccount" WHERE "username"=$1`,in.Username).Scan(&a.ID,&a.Username,&a.Role,&hash);ip:=adminClientIP(r);if e!=nil||!adminVerify(in.Password,hash){s.adminAddLog(r.Context(),nil,"登录失败","system","管理员登录失败",ip);writeJSON(w,401,map[string]string{"error":"用户名或密码错误"});return};if len(hash)==64{if next,e:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);e==nil{_,_=s.db.Exec(r.Context(),`UPDATE "AdminAccount" SET "password"=$2,"updatedAt"=NOW() WHERE "id"=$1`,a.ID,string(next))}};token:=adminNewToken();_,e=s.db.Exec(r.Context(),`INSERT INTO "AdminSession" ("id","adminId","token","expiresAt","createdAt") VALUES ($1,$2,$3,$4,NOW())`,newID(),a.ID,token,time.Now().Add(2*time.Hour));if e!=nil{dbError(w,e);return};_,_=s.db.Exec(r.Context(),`DELETE FROM "AdminSession" WHERE "adminId"=$1 AND "expiresAt"<NOW()`,a.ID);s.adminAddLog(r.Context(),&a,"登录","system","管理员登录",ip);http.SetCookie(w,&http.Cookie{Name:"admin_token",Value:token,Path:"/api/admin",HttpOnly:true,SameSite:http.SameSiteStrictMode,Secure:strings.EqualFold(envOrDefault("NODE_ENV",""),"production"),MaxAge:2*60*60});writeJSON(w,200,map[string]any{"token":token,"admin":map[string]string{"id":a.ID,"username":a.Username,"role":a.Role}})}
func (s *Server) adminLogout(w http.ResponseWriter,r *http.Request,_ adminAccount,token string){_,_=s.db.Exec(r.Context(),`DELETE FROM "AdminSession" WHERE "token"=$1`,token);http.SetCookie(w,&http.Cookie{Name:"admin_token",Value:"",Path:"/api/admin",HttpOnly:true,SameSite:http.SameSiteStrictMode,MaxAge:-1});writeJSON(w,200,map[string]bool{"success":true})}
func (s *Server) adminMe(w http.ResponseWriter,_ *http.Request,a adminAccount,_ string){writeJSON(w,200,map[string]string{"id":a.ID,"username":a.Username,"role":a.Role})}

func (s *Server) adminCount(ctx context.Context, table string, unavailable *[]string, metric string) int64 { var n int64;if e:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM `+table).Scan(&n);e!=nil{*unavailable=append(*unavailable,metric);return 0};return n }
func (s *Server) adminOnline(ctx context.Context) (int64,bool) { if s.redis==nil{return 0,false};var cursor uint64;seen:=map[string]bool{};for{keys,next,e:=s.redis.Scan(ctx,cursor,"online:*",200).Result();if e!=nil{return 0,false};for _,k:=range keys{seen[k]=true};cursor=next;if cursor==0{break}};return int64(len(seen)),true }

func (s *Server) adminDashboard(w http.ResponseWriter,r *http.Request,_ adminAccount,_ string){unavailable:=[]string{};ctx:=r.Context();totalUsers:=s.adminCount(ctx,`"User"`,&unavailable,"totalUsers");banned:=int64(0);if e:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "User" WHERE "isBanned"=true`).Scan(&banned);e!=nil{unavailable=append(unavailable,"bannedUsers")};moments:=s.adminCount(ctx,`"Moment"`,&unavailable,"totalMoments");comments:=s.adminCount(ctx,`"MomentComment"`,&unavailable,"totalComments");media:=s.adminCount(ctx,`"MediaFile"`,&unavailable,"totalMedia");privateMsgs:=s.adminCount(ctx,`"PrivateMessage"`,&unavailable,"privateMessages");groupMsgs:=s.adminCount(ctx,`"GroupMessage"`,&unavailable,"groupMessages");ipBlacklist:=s.adminCount(ctx,`"IpBlacklist"`,&unavailable,"totalIpBlacklist");announcements:=s.adminCount(ctx,`"Announcement"`,&unavailable,"totalAnnouncements");pendingReports:=int64(0);if e:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "Report" WHERE "status"='pending'`).Scan(&pendingReports);e!=nil{unavailable=append(unavailable,"pendingReports")};sensitive:=int64(0);if e:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "SensitiveWord" WHERE "isActive"=true`).Scan(&sensitive);e!=nil{unavailable=append(unavailable,"totalSensitiveWords")};loginLogs:=s.adminCount(ctx,`"LoginLog"`,&unavailable,"totalLoginLogs");illegal:=s.adminCount(ctx,`"IllegalRequest"`,&unavailable,"totalIllegalRequests");online,ok:=s.adminOnline(ctx);if !ok{unavailable=append(unavailable,"onlineUsers")};daily:=s.adminDaily(ctx,&unavailable);types:=s.adminMessageTypes(ctx,&unavailable);recentUsers:=s.adminRecentUsers(ctx);recentMoments:=s.adminRecentMoments(ctx);recentLogins:=s.adminRecentLogins(ctx);writeJSON(w,200,map[string]any{"overview":map[string]any{"totalUsers":totalUsers,"onlineUsers":online,"bannedUsers":banned,"totalMessages":privateMsgs+groupMsgs,"pendingReports":pendingReports,"totalSensitiveWords":sensitive,"totalAnnouncements":announcements},"dailyStats":daily,"messageTypes":types,"stats":map[string]any{"totalUsers":totalUsers,"bannedUsers":banned,"totalMoments":moments,"totalComments":comments,"totalMedia":media,"totalLoginLogs":loginLogs,"totalIpBlacklist":ipBlacklist,"totalIllegalRequests":illegal},"recentUsers":recentUsers,"recentMoments":recentMoments,"recentLogins":recentLogins,"unavailableMetrics":unavailable})}

func (s *Server) adminDaily(ctx context.Context, unavailable *[]string) []map[string]any { start:=time.Now().Local();start=time.Date(start.Year(),start.Month(),start.Day(),0,0,0,0,start.Location()).AddDate(0,0,-6);out:=[]map[string]any{};for i:=0;i<7;i++{from:=start.AddDate(0,0,i);to:=from.AddDate(0,0,1);var users,pm,gm,active int64;e1:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "User" WHERE "createdAt">=$1 AND "createdAt"<$2`,from,to).Scan(&users);e2:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "PrivateMessage" WHERE "createdAt">=$1 AND "createdAt"<$2`,from,to).Scan(&pm);e3:=s.db.QueryRow(ctx,`SELECT COUNT(*) FROM "GroupMessage" WHERE "createdAt">=$1 AND "createdAt"<$2`,from,to).Scan(&gm);e4:=s.db.QueryRow(ctx,`SELECT COUNT(DISTINCT "senderId") FROM (SELECT "senderId" FROM "PrivateMessage" WHERE "createdAt">=$1 AND "createdAt"<$2 UNION SELECT "senderId" FROM "GroupMessage" WHERE "createdAt">=$1 AND "createdAt"<$2) t`,from,to).Scan(&active);if e1!=nil||e2!=nil||e3!=nil||e4!=nil{*unavailable=append(*unavailable,"dailyStats")};out=append(out,map[string]any{"date":from.Format("1/2"),"newUsers":users,"activeUsers":active,"messages":pm+gm})};return out }
func (s *Server) adminMessageTypes(ctx context.Context, unavailable *[]string) []map[string]any { rows,e:=s.db.Query(ctx,`SELECT "msgType",SUM(n) FROM (SELECT "msgType",COUNT(*)::bigint n FROM "PrivateMessage" GROUP BY "msgType" UNION ALL SELECT "msgType",COUNT(*)::bigint n FROM "GroupMessage" GROUP BY "msgType") x GROUP BY "msgType" ORDER BY SUM(n) DESC`);if e!=nil{*unavailable=append(*unavailable,"messageTypes");return []map[string]any{}};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var typ string;var n int64;if rows.Scan(&typ,&n)==nil{out=append(out,map[string]any{"type":typ,"count":n})}};return out }
func (s *Server) adminRecentUsers(ctx context.Context) []map[string]any { rows,e:=s.db.Query(ctx,`SELECT "id","username","nickname","email","isBanned","createdAt" FROM "User" ORDER BY "createdAt" DESC LIMIT 5`);if e!=nil{return []map[string]any{}};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,name string;var nick,email *string;var banned bool;var t time.Time;if rows.Scan(&id,&name,&nick,&email,&banned,&t)==nil{out=append(out,map[string]any{"id":id,"username":name,"nickname":nick,"email":email,"isBanned":banned,"createdAt":t})}};return out }
func (s *Server) adminRecentMoments(ctx context.Context) []map[string]any { rows,e:=s.db.Query(ctx,`SELECT m."id",m."content",m."createdAt",u."username",u."nickname" FROM "Moment" m JOIN "User" u ON u."id"=m."userId" ORDER BY m."createdAt" DESC LIMIT 5`);if e!=nil{return []map[string]any{}};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,content,name string;var nick *string;var t time.Time;if rows.Scan(&id,&content,&t,&name,&nick)==nil{out=append(out,map[string]any{"id":id,"content":content,"createdAt":t,"user":map[string]any{"username":name,"nickname":nick}})}};return out }
func (s *Server) adminRecentLogins(ctx context.Context) []map[string]any { rows,e:=s.db.Query(ctx,`SELECT "id","userId","username","email","phone","ip","userAgent","country","city","success","failReason","loginType","createdAt" FROM "LoginLog" ORDER BY "createdAt" DESC LIMIT 5`);if e!=nil{return []map[string]any{}};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id string;var uid,name,email,phone,ip,ua,country,city,fail,typ *string;var good bool;var t time.Time;if rows.Scan(&id,&uid,&name,&email,&phone,&ip,&ua,&country,&city,&good,&fail,&typ,&t)==nil{out=append(out,map[string]any{"id":id,"userId":uid,"username":name,"email":email,"phone":phone,"ip":ip,"userAgent":ua,"country":country,"city":city,"success":good,"failReason":fail,"loginType":typ,"createdAt":t})}};return out }

func (s *Server) adminUsers(w http.ResponseWriter,r *http.Request,_ adminAccount,_ string){search:=groupQuery(r,"search");page:=intQuery(r,"page",1);size:=intQuery(r,"pageSize",20);if size>100{size=100};status:=groupQuery(r,"status");where:=`WHERE true`;args:=[]any{};if search!=""{args=append(args,search);p:="$"+strconv.Itoa(len(args));where+=` AND (u."username" ILIKE '%'||`+p+`||'%' OR COALESCE(u."email",'') ILIKE '%'||`+p+`||'%' OR COALESCE(u."nickname",'') ILIKE '%'||`+p+`||'%' OR COALESCE(u."phone",'') ILIKE '%'||`+p+`||'%')`};if status=="banned"||status=="active"{args=append(args,status=="banned");where+=` AND u."isBanned"=$`+strconv.Itoa(len(args))};var total int; if e:=s.db.QueryRow(r.Context(),`SELECT COUNT(*) FROM "User" u `+where,args...).Scan(&total);e!=nil{dbError(w,e);return};args=append(args,size,(page-1)*size);q:=`SELECT u."id",u."username",u."nickname",u."email",u."phone",u."avatar",u."bio",u."isBanned",u."banReason",u."role",u."createdAt",u."updatedAt",u."lastLoginAt",u."lastLoginIp",(SELECT COUNT(*) FROM "Moment" m WHERE m."userId"=u."id") FROM "User" u `+where+` ORDER BY u."createdAt" DESC LIMIT $`+strconv.Itoa(len(args)-1)+` OFFSET $`+strconv.Itoa(len(args));rows,e:=s.db.Query(r.Context(),q,args...);if e!=nil{dbError(w,e);return};defer rows.Close();users:=[]map[string]any{};for rows.Next(){var id,name,role string;var nick,email,phone,av,bio,reason,lastIP *string;var banned bool;var created,updated time.Time;var last *time.Time;var posts int;if rows.Scan(&id,&name,&nick,&email,&phone,&av,&bio,&banned,&reason,&role,&created,&updated,&last,&lastIP,&posts)==nil{users=append(users,map[string]any{"id":id,"username":name,"nickname":nick,"email":email,"phone":phone,"avatar":av,"bio":bio,"isBanned":banned,"banReason":reason,"role":role,"createdAt":created,"updatedAt":updated,"lastLoginAt":last,"lastLoginIp":lastIP,"postsCount":posts})}};writeJSON(w,200,map[string]any{"users":users,"total":total,"page":page,"pageSize":size})}
func (s *Server) adminUser(w http.ResponseWriter,r *http.Request,_ adminAccount,_ string){id:=r.PathValue("id");var name,role string;var nick,email,phone,av,bio,reason,lastIP *string;var banned bool;var created,updated time.Time;var last *time.Time;var posts int;e:=s.db.QueryRow(r.Context(),`SELECT u."username",u."role",u."nickname",u."email",u."phone",u."avatar",u."bio",u."isBanned",u."banReason",u."createdAt",u."updatedAt",u."lastLoginAt",u."lastLoginIp",(SELECT COUNT(*) FROM "Moment" m WHERE m."userId"=u."id") FROM "User" u WHERE u."id"=$1`,id).Scan(&name,&role,&nick,&email,&phone,&av,&bio,&banned,&reason,&created,&updated,&last,&lastIP,&posts);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户不存在"});return};if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"user":map[string]any{"id":id,"username":name,"nickname":nick,"email":email,"phone":phone,"avatar":av,"bio":bio,"isBanned":banned,"banReason":reason,"role":role,"createdAt":created,"updatedAt":updated,"lastLoginAt":last,"lastLoginIp":lastIP,"postsCount":posts}})}
func (s *Server) adminBanUser(w http.ResponseWriter,r *http.Request,a adminAccount,_ string){if !adminAllowed(a){writeJSON(w,403,map[string]string{"error":"权限不足"});return};var in struct{Ban bool `json:"ban"`;Reason string `json:"reason"`};if decode(r,&in)!=nil{groupBad(w,"请求无效");return};id:=r.PathValue("id");var name string;e:=s.db.QueryRow(r.Context(),`SELECT "username" FROM "User" WHERE "id"=$1`,id).Scan(&name);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户不存在"});return};if e!=nil{dbError(w,e);return};reason:=in.Reason;if in.Ban&&reason==""{reason="管理员操作"};_,e=s.db.Exec(r.Context(),`UPDATE "User" SET "isBanned"=$2,"banReason"=CASE WHEN $2 THEN $3 ELSE NULL END,"updatedAt"=NOW() WHERE "id"=$1`,id,in.Ban,reason);if e!=nil{dbError(w,e);return};if in.Ban{_,_=s.db.Exec(r.Context(),`DELETE FROM "UserSession" WHERE "userId"=$1`,id)};s.adminAddLog(r.Context(),&a,map[bool]string{true:"封禁用户",false:"解封用户"}[in.Ban],"user:"+id,name,adminClientIP(r));var user map[string]any;var banned bool;var why *string;_=s.db.QueryRow(r.Context(),`SELECT "isBanned","banReason" FROM "User" WHERE "id"=$1`,id).Scan(&banned,&why);user=map[string]any{"id":id,"username":name,"isBanned":banned,"banReason":why};writeJSON(w,200,map[string]any{"success":true,"user":user})}
func (s *Server) adminLogs(w http.ResponseWriter,r *http.Request,_ adminAccount,_ string){page:=intQuery(r,"page",1);var total int; if e:=s.db.QueryRow(r.Context(),`SELECT COUNT(*) FROM "AdminLog"`).Scan(&total);e!=nil{dbError(w,e);return};rows,e:=s.db.Query(r.Context(),`SELECT "id","adminId","adminName","action","target","detail","ip","createdAt" FROM "AdminLog" ORDER BY "createdAt" DESC LIMIT 20 OFFSET $1`,(page-1)*20);if e!=nil{dbError(w,e);return};defer rows.Close();logs:=[]map[string]any{};for rows.Next(){var id,action string;var aid,name,target,detail,ip *string;var created time.Time;if rows.Scan(&id,&aid,&name,&action,&target,&detail,&ip,&created)==nil{logs=append(logs,map[string]any{"id":id,"adminId":aid,"adminName":name,"action":action,"target":target,"detail":detail,"ip":ip,"createdAt":created})}};writeJSON(w,200,map[string]any{"logs":logs,"total":total,"page":page})}
