package api

import (
 "crypto/hmac"
 "crypto/sha256"
 "encoding/hex"
 "encoding/json"
 "net/http"
 "regexp"
 "sort"
 "time"
 "github.com/jackc/pgx/v5"
)
var cryptoB64=regexp.MustCompile(`^[A-Za-z0-9+/=]+$`)
func (s *Server) putCrypto(r *http.Request,key string,value any) error { b,e:=json.Marshal(value);if e!=nil{return e};_,e=s.db.Exec(r.Context(),`INSERT INTO "SystemConfig" ("key","value","updatedAt") VALUES ($1,$2,NOW()) ON CONFLICT ("key") DO UPDATE SET "value"=EXCLUDED."value","updatedAt"=NOW()`,key,string(b));return e }
func (s *Server) getCrypto(r *http.Request,key string,dst any) error {var raw string;e:=s.db.QueryRow(r.Context(),`SELECT "value" FROM "SystemConfig" WHERE "key"=$1`,key).Scan(&raw);if e!=nil{return e};return json.Unmarshal([]byte(raw),dst)}
func (s *Server) cryptoRegisterKey(w http.ResponseWriter,r *http.Request){var in struct{UserID string `json:"userId"`;PublicKey string `json:"publicKey"`;DeviceID string `json:"deviceId"`};if decode(r,&in)!=nil||in.UserID==""||in.PublicKey==""{writeJSON(w,400,map[string]string{"error":"缺少必要参数"});return};if len(in.PublicKey)<40||!cryptoB64.MatchString(in.PublicKey){writeJSON(w,400,map[string]string{"error":"公钥格式无效"});return};if in.DeviceID==""{in.DeviceID="default"};if e:=s.putCrypto(r,"e2ee:pubkey:"+in.UserID+":"+in.DeviceID,map[string]any{"publicKey":in.PublicKey,"updatedAt":time.Now().UTC().Format(time.RFC3339)});e!=nil{writeJSON(w,500,map[string]string{"error":"注册公钥失败"});return};writeJSON(w,200,map[string]bool{"success":true})}
func (s *Server) cryptoGetKey(w http.ResponseWriter,r *http.Request){id:=r.URL.Query().Get("userId");if id==""{writeJSON(w,400,map[string]string{"error":"缺少 userId"});return};device:=r.URL.Query().Get("deviceId");if device==""{device="default"};var data struct{PublicKey string `json:"publicKey"`;UpdatedAt string `json:"updatedAt"`};e:=s.getCrypto(r,"e2ee:pubkey:"+id+":"+device,&data);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"未找到公钥"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"获取公钥失败"});return};writeJSON(w,200,data)}
func (s *Server) cryptoVerifyMessage(w http.ResponseWriter,r *http.Request){var in struct{Message string `json:"message"`;Signature string `json:"signature"`;SenderID string `json:"senderId"`};if decode(r,&in)!=nil||in.Message==""||in.Signature==""||in.SenderID==""{writeJSON(w,400,map[string]string{"error":"缺少必要参数"});return};var data struct{PublicKey string `json:"publicKey"`};e:=s.getCrypto(r,"e2ee:pubkey:"+in.SenderID+":default",&data);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"发送者公钥未注册"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"验证失败"});return};key:=sha256.Sum256([]byte(data.PublicKey));m:=hmac.New(sha256.New,[]byte(hex.EncodeToString(key[:]))) ;_,_=m.Write([]byte(in.Message));expected:=m.Sum(nil);got,e:=hex.DecodeString(in.Signature);writeJSON(w,200,map[string]bool{"valid":e==nil&&hmac.Equal(got,expected)})}
type preKey struct{KeyID int `json:"keyId"`;PublicKey string `json:"publicKey"`}
func mergePreKeys(old,add []preKey)[]preKey{m:=map[int]string{};for _,v:=range old{m[v.KeyID]=v.PublicKey};for _,v:=range add{m[v.KeyID]=v.PublicKey};out:=make([]preKey,0,len(m));for id,key:=range m{out=append(out,preKey{id,key})};sort.Slice(out,func(i,j int)bool{return out[i].KeyID<out[j].KeyID});return out}
func (s *Server) getPreKeys(r *http.Request,id string)[]preKey{var list []preKey;if e:=s.getCrypto(r,"e2ee:prekeys:"+id,&list);e!=nil{return []preKey{}};return list}
func (s *Server) cryptoRegisterBundle(w http.ResponseWriter,r *http.Request){var in struct{UserID string `json:"userId"`;RegistrationID any `json:"registrationId"`;IdentityKey string `json:"identityKey"`;SigningPublicKey string `json:"signingPublicKey"`;SignedPreKey any `json:"signedPreKey"`;PreKeys []preKey `json:"preKeys"`};if decode(r,&in)!=nil||in.UserID==""||in.IdentityKey==""||in.SignedPreKey==nil{writeJSON(w,400,map[string]string{"error":"缺少必要参数"});return};var old map[string]any;_ = s.getCrypto(r,"e2ee:bundle:"+in.UserID,&old);sign:=in.SigningPublicKey;if sign==""{if v,ok:=old["signingPublicKey"].(string);ok{sign=v}else{sign=in.IdentityKey}};bundle:=map[string]any{"registrationId":in.RegistrationID,"identityKey":in.IdentityKey,"signingPublicKey":sign,"signedPreKey":in.SignedPreKey,"updatedAt":time.Now().UTC().Format(time.RFC3339)};if e:=s.putCrypto(r,"e2ee:bundle:"+in.UserID,bundle);e!=nil{writeJSON(w,500,map[string]string{"error":"注册 Bundle 失败"});return};if len(in.PreKeys)>0{if e:=s.putCrypto(r,"e2ee:prekeys:"+in.UserID,mergePreKeys(s.getPreKeys(r,in.UserID),in.PreKeys));e!=nil{writeJSON(w,500,map[string]string{"error":"注册 Bundle 失败"});return}};writeJSON(w,200,map[string]bool{"success":true})}
func (s *Server) cryptoGetBundle(w http.ResponseWriter,r *http.Request){id:=r.URL.Query().Get("userId");if id==""{writeJSON(w,400,map[string]string{"error":"缺少 userId"});return};var b map[string]any;e:=s.getCrypto(r,"e2ee:bundle:"+id,&b);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户未注册 E2EE Bundle"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"获取 Bundle 失败"});return};keys:=s.getPreKeys(r,id);var picked any=nil;if len(keys)>0{picked=keys[0];if e:=s.putCrypto(r,"e2ee:prekeys:"+id,keys[1:]);e!=nil{writeJSON(w,500,map[string]string{"error":"获取 Bundle 失败"});return}};writeJSON(w,200,map[string]any{"registrationId":b["registrationId"],"identityKey":b["identityKey"],"signingPublicKey":b["signingPublicKey"],"signedPreKey":b["signedPreKey"],"preKey":picked})}
func (s *Server) cryptoPreKeyCount(w http.ResponseWriter,r *http.Request){id:=r.URL.Query().Get("userId");if id==""{writeJSON(w,400,map[string]string{"error":"缺少 userId"});return};writeJSON(w,200,map[string]int{"count":len(s.getPreKeys(r,id))})}
func (s *Server) cryptoReplenishPreKeys(w http.ResponseWriter,r *http.Request){var in struct{UserID string `json:"userId"`;PreKeys []preKey `json:"preKeys"`};if decode(r,&in)!=nil||in.UserID==""||len(in.PreKeys)==0{writeJSON(w,400,map[string]string{"error":"缺少必要参数"});return};keys:=mergePreKeys(s.getPreKeys(r,in.UserID),in.PreKeys);if e:=s.putCrypto(r,"e2ee:prekeys:"+in.UserID,keys);e!=nil{writeJSON(w,500,map[string]string{"error":"补充失败"});return};writeJSON(w,200,map[string]any{"success":true,"totalCount":len(keys)})}
