package api

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

var groupUsernameRE = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_]{4,31}$`)

// registerGroupRoutes mirrors the routes mounted by server/group-message.ts
// and server/burn-message.ts.  The request shapes intentionally keep the
// Node-era userId/operatorId fields so the same clients can be replayed.
func (s *Server) registerGroupRoutes(mux *http.ServeMux) {
	routes := []struct{ method, path string; handler http.HandlerFunc }{
		{"POST", "/api/group/send", s.groupSend}, {"GET", "/api/group/messages", s.groupMessages},
		{"POST", "/api/group/ack", s.groupAck}, {"GET", "/api/group/unread", s.groupUnread},
		{"POST", "/api/group/create", s.groupCreate}, {"GET", "/api/group/list", s.groupList},
		{"GET", "/api/group/info", s.groupInfo}, {"GET", "/api/group/members", s.groupMembers},
		{"POST", "/api/group/join", s.groupJoin}, {"GET", "/api/group/search", s.groupSearch},
		{"POST", "/api/group/invite/create", s.groupInviteCreate}, {"GET", "/api/group/invite/list", s.groupInviteList},
		{"POST", "/api/group/invite/revoke", s.groupInviteRevoke}, {"POST", "/api/group/invite/join", s.groupInviteJoin},
		{"GET", "/api/group/peer/resolve", s.groupPeerResolve}, {"POST", "/api/group/username/set", s.groupUsernameSet},
		{"PUT", "/api/group/update/name", s.groupUpdateName}, {"PUT", "/api/group/update/avatar", s.groupUpdateAvatar},
		{"PUT", "/api/group/update/username", s.groupUpdateUsername}, {"PUT", "/api/group/update", s.groupUpdate},
		{"POST", "/api/group/leave", s.groupLeave}, {"POST", "/api/group/kick", s.groupKick},
		{"POST", "/api/group/transfer", s.groupTransfer}, {"POST", "/api/group/admin/set", s.groupAdminSet},
		{"PUT", "/api/group/announcement", s.groupAnnouncement}, {"PUT", "/api/group/member/nickname", s.groupMemberNickname},
		{"POST", "/api/group/mute", s.groupMute}, {"POST", "/api/group/dissolve", s.groupDissolve},
		{"POST", "/api/group/qrcode", s.groupQRCode}, {"POST", "/api/group/invite-members", s.groupInviteMembers},
		{"GET", "/api/group/invites", s.groupInvites}, {"POST", "/api/group/invite-accept/{inviteId}", s.groupInviteAccept},
		{"POST", "/api/group/invite-reject/{inviteId}", s.groupInviteReject}, {"POST", "/api/group/burn-message", s.groupBurnMessage},
	}
	for _, route := range routes { mux.HandleFunc(route.method+" "+route.path, route.handler) }
}

func groupBad(w http.ResponseWriter, msg string) { writeJSON(w, http.StatusBadRequest, map[string]string{"error": msg}) }
func groupErr(w http.ResponseWriter, err error) { if err == pgx.ErrNoRows { writeJSON(w, 404, map[string]string{"error": "群组不存在"}); return }; dbError(w, err) }
func groupQuery(r *http.Request, key string) string { return strings.TrimSpace(r.URL.Query().Get(key)) }
func intQuery(r *http.Request, key string, fallback int) int { n, e := strconv.Atoi(groupQuery(r,key)); if e != nil || n <= 0 { return fallback }; return n }
func int64Body(v any) int64 { switch n:=v.(type) { case float64: return int64(n); case json.Number: x,_:=n.Int64(); return x; case int64: return n; case int: return int64(n); case string: x,_:=strconv.ParseInt(n,10,64); return x }; return 0 }
func groupPublicURL(path string) string { base:=strings.TrimRight(os.Getenv("PUBLIC_BASE_URL"),"/"); if base=="" { return path }; return base+path }
func groupJSONExtra(v *string) any { if v==nil || *v=="" { return nil }; var x any; if json.Unmarshal([]byte(*v),&x)==nil{return x}; return nil }
func groupRole(ctx context.Context, s *Server, gid, uid string) (string,error) { var role string; e:=s.db.QueryRow(ctx,`SELECT "role" FROM "GroupMember" WHERE "groupId"=$1 AND "userId"=$2`,gid,uid).Scan(&role); return role,e }
func groupRequireRole(ctx context.Context,s *Server,gid,uid string,roles ...string) (bool,error) { role,e:=groupRole(ctx,s,gid,uid); if e!=nil{return false,e}; for _,r:=range roles {if role==r{return true,nil}}; return false,nil }

func (s *Server) groupSend(w http.ResponseWriter,r *http.Request) {
	var in struct{ GroupID,SenderID,SenderName,MsgType,Content,ReplyToID string; Extra json.RawMessage `json:"extra"` }
	if decode(r,&in)!=nil || in.GroupID=="" || in.SenderID=="" || in.Content=="" { groupBad(w,"缺少必要参数"); return }
	if in.MsgType=="" { in.MsgType="mls_encrypted" }
	if in.MsgType!="mls_encrypted" && in.MsgType!="system" { writeJSON(w,400,map[string]string{"error":"群聊强制要求 MLS 加密，拒绝写入明文业务消息"}); return }
	if _,e:=groupRole(r.Context(),s,in.GroupID,in.SenderID); e!=nil { if e==pgx.ErrNoRows {writeJSON(w,403,map[string]string{"error":"非群成员"})} else {dbError(w,e)}; return }
	var last int64; if e:=s.db.QueryRow(r.Context(),`SELECT "lastMsgSeq" FROM "Group" WHERE "id"=$1 FOR UPDATE`,in.GroupID).Scan(&last); e!=nil {groupErr(w,e); return}
	seq:=last+1; now:=time.Now(); id:=newID(); var extra *string; if len(in.Extra)>0 && string(in.Extra)!="null" {x:=string(in.Extra); extra=&x}
	_,e:=s.db.Exec(r.Context(),`INSERT INTO "GroupMessage" ("id","groupId","seq","senderId","senderName","msgType","content","replyToId","extra","mlsEncrypted","mlsEpoch","createdAt") VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,NULLIF($8,''),$9,$10,0,$11)`,id,in.GroupID,seq,in.SenderID,in.SenderName,in.MsgType,in.Content,in.ReplyToID,extra,in.MsgType=="mls_encrypted",now); if e!=nil {dbError(w,e); return}
	_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "lastMsgSeq"=$2,"lastMsgTime"=$3,"updatedAt"=$3 WHERE "id"=$1`,in.GroupID,seq,now); if e!=nil {dbError(w,e); return}
	msg:=map[string]any{"type":"group_message","groupId":in.GroupID,"seq":seq,"senderId":in.SenderID,"senderName":in.SenderName,"msgType":in.MsgType,"content":in.Content,"timestamp":now.UnixMilli()}; if in.ReplyToID!=""{msg["replyToId"]=in.ReplyToID}; if x:=groupJSONExtra(extra);x!=nil{msg["extra"]=x}
	if s.redis!=nil { var members []string; rows,_:=s.db.Query(r.Context(),`SELECT "userId" FROM "GroupMember" WHERE "groupId"=$1 AND "userId"<>$2`,in.GroupID,in.SenderID); if rows!=nil {for rows.Next(){var uid string; if rows.Scan(&uid)==nil{members=append(members,uid)}}; rows.Close()}; for _,uid:=range members {b,_:=json.Marshal(map[string]any{"userId":uid,"payload":msg}); _=s.redis.Publish(r.Context(),imPushChannel,b).Err()} }
	writeJSON(w,200,map[string]any{"ok":true,"seq":seq,"timestamp":now.UnixMilli()})
}

func (s *Server) groupMessages(w http.ResponseWriter,r *http.Request) {
	gid,uid:=groupQuery(r,"groupId"),groupQuery(r,"userId"); if gid==""||uid==""{groupBad(w,"缺少 groupId 或 userId");return}; ok,e:=groupRequireRole(r.Context(),s,gid,uid,"owner","admin","member"); if e!=nil||!ok {if e!=nil&&e!=pgx.ErrNoRows{dbError(w,e)}else{writeJSON(w,403,map[string]string{"error":"非群成员，无权拉取消息"})};return}
	limit:=intQuery(r,"limit",50); if limit>100{limit=100}; after,before:=groupQuery(r,"afterSeq"),groupQuery(r,"beforeSeq"); order:="DESC"; clause:=""; var arg any=gid; if after!="" {clause=` AND "seq">$2`; order="ASC";arg=after} else if before!="" {clause=` AND "seq"<$2`;order="DESC";arg=before}
	q:=`SELECT gm."id",gm."seq",gm."senderId",COALESCE(gm."senderName",''),gm."msgType",gm."content",gm."replyToId",gm."extra",gm."createdAt",gm."isRevoked",COALESCE(u."avatar",'') FROM "GroupMessage" gm LEFT JOIN "User" u ON u."id"=gm."senderId" WHERE gm."groupId"=$1`+clause+` ORDER BY gm."seq" `+order+` LIMIT `+strconv.Itoa(limit+1)
	rows,e:=s.db.Query(r.Context(),q,arg);if e!=nil{dbError(w,e);return};defer rows.Close(); msgs:=[]map[string]any{};for rows.Next(){var id,sid,name,typ,content,av string;var seq int64;var reply,extra *string;var created time.Time;var revoked bool;if e=rows.Scan(&id,&seq,&sid,&name,&typ,&content,&reply,&extra,&created,&revoked,&av);e!=nil{dbError(w,e);return};m:=map[string]any{"id":id,"seq":seq,"senderId":sid,"senderName":name,"senderAvatar":av,"msgType":typ,"content":content,"createdAt":created.UTC().Format(time.RFC3339Nano),"isRevoked":revoked};if reply!=nil{m["replyToId"]=*reply};if x:=groupJSONExtra(extra);x!=nil{m["extra"]=x};msgs=append(msgs,m)}
	hasMore:=len(msgs)>limit;if hasMore{msgs=msgs[:limit]};if order=="DESC"{for i,j:=0,len(msgs)-1;i<j;i,j=i+1,j-1{msgs[i],msgs[j]=msgs[j],msgs[i]}};var latest int64;_=s.db.QueryRow(r.Context(),`SELECT "lastMsgSeq" FROM "Group" WHERE "id"=$1`,gid).Scan(&latest);writeJSON(w,200,map[string]any{"messages":msgs,"hasMore":hasMore,"latestSeq":latest})
}

func (s *Server) groupAck(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID string;LastAckSeq any `json:"lastAckSeq"`};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};n:=int64Body(in.LastAckSeq);var latest int64;e:=s.db.QueryRow(r.Context(),`UPDATE "GroupMember" SET "lastAckSeq"=$3 WHERE "groupId"=$1 AND "userId"=$2 RETURNING (SELECT "lastMsgSeq" FROM "Group" WHERE "id"=$1)`,in.GroupID,in.UserID,n).Scan(&latest);if e!=nil{dbError(w,e);return};u:=latest-n;if u<0{u=0};writeJSON(w,200,map[string]any{"ok":true,"unread":u})}
func (s *Server) groupUnread(w http.ResponseWriter,r *http.Request){uid:=groupQuery(r,"userId");if uid==""{groupBad(w,"缺少 userId");return};rows,e:=s.db.Query(r.Context(),`SELECT m."groupId",GREATEST(0,g."lastMsgSeq"-m."lastAckSeq") FROM "GroupMember" m JOIN "Group" g ON g."id"=m."groupId" WHERE m."userId"=$1`,uid);if e!=nil{dbError(w,e);return};defer rows.Close();out:=map[string]int64{};for rows.Next(){var gid string;var n int64;if rows.Scan(&gid,&n)==nil&&n>0{out[gid]=n}};writeJSON(w,200,out)}

func (s *Server) groupCreate(w http.ResponseWriter,r *http.Request){var in struct{Name,OwnerID string;MemberIDs []string `json:"memberIds"`;Type string;MaxMembers int `json:"maxMembers"`;Username string;IsPublic bool `json:"isPublic"`};if decode(r,&in)!=nil||in.Name==""||in.OwnerID==""{groupBad(w,"缺少必要参数");return};if in.Username!=""&&!groupUsernameRE.MatchString(in.Username){groupBad(w,"群组用户名必须以字母开头，5-32位字母数字下划线");return};if in.MaxMembers<=0{in.MaxMembers=500};typ:=in.Type;if typ==""{typ="normal"};if typ!="channel"&&in.MaxMembers>200{typ="super"};if typ=="channel"{in.MaxMembers=0};gid,did:=newID(),fmt.Sprintf("-100%s",strings.TrimPrefix(newID(),"c")[:10]);count:=1;for _,id:=range in.MemberIDs{if id!=in.OwnerID{count++}};tx,e:=s.db.Begin(r.Context());if e!=nil{dbError(w,e);return};defer tx.Rollback(r.Context());_,e=tx.Exec(r.Context(),`INSERT INTO "Group" ("id","dialogId","name","username","ownerId","type","isPublic","maxMembers","memberCount","createdAt","updatedAt") VALUES ($1,$2,$3,NULLIF($4,''),$5,$6,$7,$8,$9,NOW(),NOW())`,gid,did,in.Name,in.Username,in.OwnerID,typ,in.IsPublic,in.MaxMembers,count);if e!=nil{dbError(w,e);return};_,e=tx.Exec(r.Context(),`INSERT INTO "GroupMember" ("id","groupId","userId","role","lastAckSeq","joinTime","createdAt","updatedAt") VALUES ($1,$2,$3,'owner',0,NOW(),NOW(),NOW())`,newID(),gid,in.OwnerID);if e!=nil{dbError(w,e);return};for _,uid:=range in.MemberIDs{if uid==in.OwnerID{continue};_,e=tx.Exec(r.Context(),`INSERT INTO "GroupMember" ("id","groupId","userId","role","lastAckSeq","joinTime","createdAt","updatedAt") VALUES ($1,$2,$3,'member',0,NOW(),NOW(),NOW())`,newID(),gid,uid);if e!=nil{dbError(w,e);return}};if e=tx.Commit(r.Context());e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"groupId":gid,"dialogId":did})}

func (s *Server) groupList(w http.ResponseWriter,r *http.Request){uid:=groupQuery(r,"userId");if uid==""{groupBad(w,"缺少 userId");return};rows,e:=s.db.Query(r.Context(),`SELECT g."id",g."dialogId",g."name",g."username",g."avatar",g."ownerId",g."type",g."isPublic",g."memberCount",g."lastMsgSeq",m."lastAckSeq",g."createdAt",g."updatedAt" FROM "GroupMember" m JOIN "Group" g ON g."id"=m."groupId" WHERE m."userId"=$1 ORDER BY g."updatedAt" DESC`,uid);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,name,owner,typ string;var dialog,username,avatar *string;var pub bool;var count,last,ack int64;var created,updated time.Time;if rows.Scan(&id,&dialog,&name,&username,&avatar,&owner,&typ,&pub,&count,&last,&ack,&created,&updated)!=nil{continue};unread:=last-ack;if unread<0{unread=0};out=append(out,map[string]any{"id":id,"groupId":id,"dialogId":dialog,"name":name,"username":username,"avatar":avatar,"ownerId":owner,"type":typ,"isPublic":pub,"memberCount":count,"lastMessage":"🔒 [加密消息]","unreadCount":unread,"createdAt":created.UnixMilli(),"updatedAt":updated.UnixMilli()})};writeJSON(w,200,map[string]any{"groups":out})}
func (s *Server) groupInfo(w http.ResponseWriter,r *http.Request){gid:=groupQuery(r,"groupId");if gid==""{groupBad(w,"缺少 groupId");return};var id,name,owner,typ string;var dialog,username,avatar,announce *string;var pub bool;var max,count,last int64;var created,updated time.Time;e:=s.db.QueryRow(r.Context(),`SELECT "id","dialogId","name","username","avatar","ownerId","type","isPublic","maxMembers","memberCount","lastMsgSeq","announcement","createdAt","updatedAt" FROM "Group" WHERE "id"=$1`,gid).Scan(&id,&dialog,&name,&username,&avatar,&owner,&typ,&pub,&max,&count,&last,&announce,&created,&updated);if e!=nil{if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"群组不存在"})}else{dbError(w,e)};return};writeJSON(w,200,map[string]any{"id":id,"dialogId":dialog,"name":name,"username":username,"avatar":avatar,"ownerId":owner,"type":typ,"isPublic":pub,"maxMembers":max,"memberCount":count,"lastMsgSeq":strconv.FormatInt(last,10),"announcement":announce,"createdAt":created,"updatedAt":updated})}
func (s *Server) groupMembers(w http.ResponseWriter,r *http.Request){gid:=groupQuery(r,"groupId");if gid==""{groupBad(w,"缺少 groupId");return};page:=intQuery(r,"page",1);size:=intQuery(r,"pageSize",100);if size>200{size=200};off:=(page-1)*size;rows,e:=s.db.Query(r.Context(),`SELECT m."id",m."userId",m."role",m."nickname",m."lastAckSeq",m."joinTime",COALESCE(u."nickname",u."username",m."userId"),COALESCE(u."avatar",'') FROM "GroupMember" m LEFT JOIN "User" u ON u."id"=m."userId" WHERE m."groupId"=$1 ORDER BY m."role",m."joinTime" LIMIT $2 OFFSET $3`,gid,size,off);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,uid,role,name,av string;var nick *string;var ack int64;var join time.Time;if rows.Scan(&id,&uid,&role,&nick,&ack,&join,&name,&av)!=nil{continue};if nick!=nil&&*nick!=""{name=*nick};out=append(out,map[string]any{"id":id,"userId":uid,"groupId":gid,"role":role,"nickname":nick,"lastAckSeq":strconv.FormatInt(ack,10),"joinTime":join,"name":name,"avatar":av})};var total int;_=s.db.QueryRow(r.Context(),`SELECT COUNT(*) FROM "GroupMember" WHERE "groupId"=$1`,gid).Scan(&total);writeJSON(w,200,map[string]any{"members":out,"total":total,"page":page,"pageSize":size,"totalPages":(total+size-1)/size})}
func (s *Server) groupJoin(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Nickname string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};var seq int64;if e:=s.db.QueryRow(r.Context(),`SELECT "lastMsgSeq" FROM "Group" WHERE "id"=$1`,in.GroupID).Scan(&seq);e!=nil{groupErr(w,e);return};_,e:=s.db.Exec(r.Context(),`INSERT INTO "GroupMember" ("id","groupId","userId","nickname","lastAckSeq","joinTime","createdAt","updatedAt") VALUES ($1,$2,$3,NULLIF($4,''),$5,NOW(),NOW(),NOW())`,newID(),in.GroupID,in.UserID,in.Nickname,seq);if e!=nil{dbError(w,e);return};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "memberCount"="memberCount"+1,"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]bool{"ok":true})}
func (s *Server) groupSearch(w http.ResponseWriter,r *http.Request){q:=groupQuery(r,"q");if q==""{groupBad(w,"请输入至少1个字符");return};rows,e:=s.db.Query(r.Context(),`SELECT "id","dialogId","username","name","avatar","memberCount","type","isPublic" FROM "Group" WHERE "id"=$1 OR "dialogId"=$1 OR "username"=$1 OR "name" ILIKE '%'||$1||'%' LIMIT 10`,q);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,name,typ string;var did,user,av *string;var n int64;var pub bool;if rows.Scan(&id,&did,&user,&name,&av,&n,&typ,&pub)==nil{out=append(out,map[string]any{"id":id,"dialogId":did,"username":user,"name":name,"avatar":av,"memberCount":n,"type":typ,"isPublic":pub})}};writeJSON(w,200,map[string]any{"groups":out})}

func (s *Server) groupInviteCreate(w http.ResponseWriter,r *http.Request){var in struct{GroupID,CreatorID,Name,ExpireAt string;ExpireHours any `json:"expireHours"`;MaxUses any `json:"maxUses"`};if decode(r,&in)!=nil||in.GroupID==""||in.CreatorID==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.CreatorID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅管理员和群主可创建邀请链接"});return};max:=int64Body(in.MaxUses);var exp *time.Time;if in.ExpireAt!=""{t,e:=time.Parse(time.RFC3339,in.ExpireAt);if e!=nil||!t.After(time.Now()){groupBad(w,"失效时间无效");return};exp=&t}else if h:=int64Body(in.ExpireHours);h>0{t:=time.Now().Add(time.Duration(h)*time.Hour);exp=&t};hash:=newID();id:=newID();_,e=s.db.Exec(r.Context(),`INSERT INTO "InviteLink" ("id","hash","groupId","creatorId","name","expireAt","maxUses","usedCount","isRevoked","createdAt","updatedAt") VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,0,false,NOW(),NOW())`,id,hash,in.GroupID,in.CreatorID,in.Name,exp,max);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"inviteLink":map[string]any{"id":id,"hash":hash,"url":"/im/+"+hash,"fullUrl":groupPublicURL("/im/+"+hash),"name":nilIfEmpty(in.Name),"expireAt":exp,"maxUses":max,"usedCount":0}})}
func (s *Server) groupInviteList(w http.ResponseWriter,r *http.Request){gid:=groupQuery(r,"groupId");if gid==""{groupBad(w,"缺少 groupId");return};rows,e:=s.db.Query(r.Context(),`SELECT "id","hash","name","creatorId","expireAt","maxUses","usedCount","createdAt" FROM "InviteLink" WHERE "groupId"=$1 AND "isRevoked"=false ORDER BY "createdAt" DESC`,gid);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,hash,creator string;var name *string;var exp,created *time.Time;var max,used int64;if rows.Scan(&id,&hash,&name,&creator,&exp,&max,&used,&created)!=nil{continue};expired:=(exp!=nil&&time.Now().After(*exp))||(max>0&&used>=max);var rem any;if max>0{rem=max-used;if int64Body(rem)<0{rem=int64(0)}};out=append(out,map[string]any{"id":id,"hash":hash,"url":"/im/+"+hash,"fullUrl":groupPublicURL("/im/+"+hash),"name":name,"creatorId":creator,"expireAt":exp,"maxUses":max,"usedCount":used,"remainingUses":rem,"isExpired":expired,"createdAt":created})};writeJSON(w,200,map[string]any{"links":out})}
func (s *Server) groupInviteRevoke(w http.ResponseWriter,r *http.Request){var in struct{Hash,CreatorID string};if decode(r,&in)!=nil||in.Hash==""||in.CreatorID==""{groupBad(w,"缺少必要参数");return};var gid,creator string;if e:=s.db.QueryRow(r.Context(),`SELECT "groupId","creatorId" FROM "InviteLink" WHERE "hash"=$1`,in.Hash).Scan(&gid,&creator);e!=nil{writeJSON(w,404,map[string]string{"error":"邀请链接不存在"});return};if creator!=in.CreatorID{ok,_:=groupRequireRole(r.Context(),s,gid,in.CreatorID,"owner");if !ok{writeJSON(w,403,map[string]string{"error":"无权撤销此链接"});return}};_,e:=s.db.Exec(r.Context(),`UPDATE "InviteLink" SET "isRevoked"=true,"updatedAt"=NOW() WHERE "hash"=$1`,in.Hash);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]bool{"ok":true})}
func (s *Server) groupInviteJoin(w http.ResponseWriter,r *http.Request){var in struct{Hash,UserID,Nickname string};if decode(r,&in)!=nil||in.Hash==""||in.UserID==""{groupBad(w,"缺少必要参数");return};var gid,name string;var exp *time.Time;var max,used,count,cap int64;var revoked bool;e:=s.db.QueryRow(r.Context(),`SELECT l."groupId",g."name",l."expireAt",l."maxUses",l."usedCount",l."isRevoked",g."memberCount",g."maxMembers" FROM "InviteLink" l JOIN "Group" g ON g."id"=l."groupId" WHERE l."hash"=$1`,in.Hash).Scan(&gid,&name,&exp,&max,&used,&revoked,&count,&cap);if e!=nil{writeJSON(w,404,map[string]string{"error":"邀请链接不存在"});return};if revoked{writeJSON(w,410,map[string]string{"error":"邀请链接已被撤销"});return};if exp!=nil&&time.Now().After(*exp){writeJSON(w,410,map[string]string{"error":"邀请链接已过期"});return};if max>0&&used>=max{writeJSON(w,410,map[string]string{"error":"邀请链接已达到最大使用次数"});return};var exists bool;_=s.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM "GroupMember" WHERE "groupId"=$1 AND "userId"=$2)`,gid,in.UserID).Scan(&exists);if exists{writeJSON(w,200,map[string]any{"ok":true,"alreadyMember":true,"groupId":gid});return};if cap>0&&count>=cap{writeJSON(w,403,map[string]string{"error":"群组已满员"});return};_,e=s.db.Exec(r.Context(),`INSERT INTO "GroupMember" ("id","groupId","userId","nickname","lastAckSeq","joinTime","createdAt","updatedAt") SELECT $1,$2,$3,NULLIF($4,''),"lastMsgSeq",NOW(),NOW(),NOW() FROM "Group" WHERE "id"=$2`,newID(),gid,in.UserID,in.Nickname);if e!=nil{dbError(w,e);return};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "memberCount"="memberCount"+1 WHERE "id"=$1`,gid);if e!=nil{dbError(w,e);return};_,_=s.db.Exec(r.Context(),`UPDATE "InviteLink" SET "usedCount"="usedCount"+1,"updatedAt"=NOW() WHERE "hash"=$1`,in.Hash);writeJSON(w,200,map[string]any{"ok":true,"groupId":gid,"groupName":name})}

func (s *Server) groupPeerResolve(w http.ResponseWriter,r *http.Request){did:=groupQuery(r,"dialogId");if did==""{groupBad(w,"缺少 dialogId");return};var id,username,nick,av,bio string;var bot bool;e:=s.db.QueryRow(r.Context(),`SELECT "id","username",COALESCE("nickname",''),COALESCE("avatar",''),COALESCE("bio",''),"isBot" FROM "User" WHERE "dialogId"=$1`,did).Scan(&id,&username,&nick,&av,&bio,&bot);if e==nil{writeJSON(w,200,map[string]any{"peerType":map[bool]string{true:"bot",false:"user"}[bot],"data":map[string]any{"id":id,"dialogId":did,"username":username,"nickname":nick,"avatar":av,"bio":bio,"isBot":bot}});return};var gid,name,typ string;var gu,av2 *string;var pub bool;var count int64;e=s.db.QueryRow(r.Context(),`SELECT "id","username","name","avatar","type","isPublic","memberCount" FROM "Group" WHERE "dialogId"=$1`,did).Scan(&gid,&gu,&name,&av2,&typ,&pub,&count);if e!=nil{writeJSON(w,404,map[string]string{"error":"群组不存在"});return};pt:="group";if typ=="channel"{pt="channel"}else if typ=="super"{pt="supergroup"};writeJSON(w,200,map[string]any{"peerType":pt,"data":map[string]any{"id":gid,"dialogId":did,"username":gu,"name":name,"avatar":av2,"type":typ,"isPublic":pub,"memberCount":count}})}
func (s *Server) groupUsernameSet(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Username string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.UserID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可设置用户名"});return};if in.Username!=""&&!groupUsernameRE.MatchString(in.Username){groupBad(w,"用户名必须以字母开头，5-32位字母数字下划线");return};if in.Username!=""{var used bool;_=s.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM "User" WHERE "username"=$1) OR EXISTS(SELECT 1 FROM "Group" WHERE "username"=$1 AND "id"<>$2)`,in.Username,in.GroupID).Scan(&used);if used{writeJSON(w,409,map[string]string{"error":"该用户名已被占用"});return}};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "username"=NULLIF($2,''),"isPublic"=($2<>''),"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID,in.Username);if e!=nil{dbError(w,e);return};var u any;if in.Username!=""{u=in.Username};var p any;if in.Username!=""{p=groupPublicURL("/im/"+in.Username)};writeJSON(w,200,map[string]any{"ok":true,"username":u,"publicUrl":p})}

func (s *Server) groupUpdateName(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Name string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""||strings.TrimSpace(in.Name)==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.UserID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可修改群名称"});return};name:=strings.TrimSpace(in.Name);if len(name)>30{groupBad(w,"群名称不能超过30个字符");return};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "name"=$2,"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID,name);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"name":name})}
func (s *Server) groupUpdateAvatar(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,DataBase64,MimeType string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.UserID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可修改群头像"});return};if in.DataBase64==""{groupBad(w,"缺少头像数据");return};raw,e:=base64.StdEncoding.DecodeString(strings.TrimPrefix(in.DataBase64,"data:"));if e!=nil||len(raw)>5<<20{groupBad(w,"头像文件过大，最大 5MB");return};rr:=httptest.NewRecorder();s.storeMedia(rr,r,user{ID:in.UserID},"image",raw,in.MimeType,"group-avatar",0,0,0,"",false);if rr.Code>=300{w.WriteHeader(rr.Code);w.Write(rr.Body.Bytes());return};var out struct{URL string `json:"url"`};if json.Unmarshal(rr.Body.Bytes(),&out)!=nil||out.URL==""{writeJSON(w,500,map[string]string{"error":"头像上传失败"});return};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "avatar"=$2,"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID,out.URL);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"avatar":out.URL,"storage":"minio"})}
func (s *Server) groupUpdateUsername(w http.ResponseWriter,r *http.Request){s.groupUsernameSet(w,r)}
func (s *Server) groupUpdate(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Name,Username,AvatarBase64,AvatarMimeType string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.UserID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可修改群信息"});return};updates:=[]string{};args:=[]any{in.GroupID};if in.Name!=""{name:=strings.TrimSpace(in.Name);if name==""||len(name)>30{groupBad(w,"群名称不能为空或超过30个字符");return};args=append(args,name);updates=append(updates,fmt.Sprintf(`"name"=$%d`,len(args)))};if in.Username!=""{if !groupUsernameRE.MatchString(in.Username){groupBad(w,"群 ID 必须以字母开头，5-32位字母数字下划线");return};args=append(args,in.Username);updates=append(updates,fmt.Sprintf(`"username"=$%d,"isPublic"=true`,len(args)))};if len(updates)==0{groupBad(w,"没有需要修改的内容");return};q:=`UPDATE "Group" SET `+strings.Join(updates,",")+`,"updatedAt"=NOW() WHERE "id"=$1`;if _,e=s.db.Exec(r.Context(),q,args...);e!=nil{dbError(w,e);return};var id,name string;var av,un *string;var pub bool;_=s.db.QueryRow(r.Context(),`SELECT "id","name","avatar","username","isPublic" FROM "Group" WHERE "id"=$1`,in.GroupID).Scan(&id,&name,&av,&un,&pub);writeJSON(w,200,map[string]any{"ok":true,"group":map[string]any{"id":id,"name":name,"avatar":av,"username":un,"isPublic":pub}})}

func (s *Server) groupLeave(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.UserID);if e!=nil{writeJSON(w,404,map[string]string{"error":"你不是该群成员"});return};if role=="owner"{writeJSON(w,403,map[string]string{"error":"群主不能直接退出群聊，请先转让群主"});return};_,e=s.db.Exec(r.Context(),`DELETE FROM "GroupMember" WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.UserID);if e!=nil{dbError(w,e);return};_,_=s.db.Exec(r.Context(),`UPDATE "Group" SET "memberCount"=GREATEST(0,"memberCount"-1) WHERE "id"=$1`,in.GroupID);writeJSON(w,200,map[string]bool{"ok":true})}
func (s *Server) groupKick(w http.ResponseWriter,r *http.Request){var in struct{GroupID,OperatorID,TargetUserID string};if decode(r,&in)!=nil||in.GroupID==""||in.OperatorID==""||in.TargetUserID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.OperatorID);if e!=nil||role!="owner"&&role!="admin"{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可以踢出成员"});return};target,e:=groupRole(r.Context(),s,in.GroupID,in.TargetUserID);if e!=nil{writeJSON(w,404,map[string]string{"error":"目标用户不是群成员"});return};if target=="owner"||(target=="admin"&&role!="owner"){writeJSON(w,403,map[string]string{"error":"不能踢出该成员"});return};_,e=s.db.Exec(r.Context(),`DELETE FROM "GroupMember" WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.TargetUserID);if e!=nil{dbError(w,e);return};_,_=s.db.Exec(r.Context(),`UPDATE "Group" SET "memberCount"=GREATEST(0,"memberCount"-1) WHERE "id"=$1`,in.GroupID);writeJSON(w,200,map[string]bool{"ok":true})}
func (s *Server) groupTransfer(w http.ResponseWriter,r *http.Request){var in struct{GroupID,OwnerID,NewOwnerID string};if decode(r,&in)!=nil||in.GroupID==""||in.OwnerID==""||in.NewOwnerID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.OwnerID);if e!=nil||role!="owner"{writeJSON(w,403,map[string]string{"error":"仅群主可以转让"});return};if _,e=groupRole(r.Context(),s,in.GroupID,in.NewOwnerID);e!=nil{writeJSON(w,404,map[string]string{"error":"目标用户不是群成员"});return};tx,e:=s.db.Begin(r.Context());if e!=nil{dbError(w,e);return};defer tx.Rollback(r.Context());if _,e=tx.Exec(r.Context(),`UPDATE "GroupMember" SET "role"='admin' WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.OwnerID);e!=nil{dbError(w,e);return};if _,e=tx.Exec(r.Context(),`UPDATE "GroupMember" SET "role"='owner' WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.NewOwnerID);e!=nil{dbError(w,e);return};if _,e=tx.Exec(r.Context(),`UPDATE "Group" SET "ownerId"=$2,"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID,in.NewOwnerID);e!=nil{dbError(w,e);return};if e=tx.Commit(r.Context());e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]bool{"ok":true})}
func (s *Server) groupAdminSet(w http.ResponseWriter,r *http.Request){var in struct{GroupID,OwnerID,TargetUserID string;IsAdmin bool};if decode(r,&in)!=nil||in.GroupID==""||in.OwnerID==""||in.TargetUserID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.OwnerID);if e!=nil||role!="owner"{writeJSON(w,403,map[string]string{"error":"仅群主可以设置管理员"});return};tr,e:=groupRole(r.Context(),s,in.GroupID,in.TargetUserID);if e!=nil{writeJSON(w,404,map[string]string{"error":"目标用户不是群成员"});return};if tr=="owner"{writeJSON(w,403,map[string]string{"error":"不能修改群主角色"});return};newRole:="member";if in.IsAdmin{newRole="admin"};_,e=s.db.Exec(r.Context(),`UPDATE "GroupMember" SET "role"=$3 WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.TargetUserID,newRole);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"role":newRole})}
func (s *Server) groupAnnouncement(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Announcement string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};ok,e:=groupRequireRole(r.Context(),s,in.GroupID,in.UserID,"owner","admin");if e!=nil||!ok{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可以设置群公告"});return};var a any;if in.Announcement!=""{a=in.Announcement};_,e=s.db.Exec(r.Context(),`UPDATE "Group" SET "announcement"=NULLIF($2,''),"updatedAt"=NOW() WHERE "id"=$1`,in.GroupID,in.Announcement);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"announcement":a})}
func (s *Server) groupMemberNickname(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID,Nickname string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};if _,e:=groupRole(r.Context(),s,in.GroupID,in.UserID);e!=nil{writeJSON(w,404,map[string]string{"error":"你不在该群中"});return};name:=strings.TrimSpace(in.Nickname);if len(name)>20{groupBad(w,"昵称不能超过20个字符");return};_,e:=s.db.Exec(r.Context(),`UPDATE "GroupMember" SET "nickname"=NULLIF($3,''),"updatedAt"=NOW() WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.UserID,name);if e!=nil{dbError(w,e);return};var out any;if name!=""{out=name};writeJSON(w,200,map[string]any{"ok":true,"nickname":out})}
func (s *Server) groupMute(w http.ResponseWriter,r *http.Request){var in struct{GroupID,OperatorID,TargetUserID string;Duration int64};if decode(r,&in)!=nil||in.GroupID==""||in.OperatorID==""||in.TargetUserID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.OperatorID);if e!=nil||role!="owner"&&role!="admin"{writeJSON(w,403,map[string]string{"error":"仅群主和管理员可以禁言"});return};tr,e:=groupRole(r.Context(),s,in.GroupID,in.TargetUserID);if e!=nil{writeJSON(w,404,map[string]string{"error":"目标用户不是群成员"});return};if tr=="owner"||(tr=="admin"&&role!="owner"){writeJSON(w,403,map[string]string{"error":"不能禁言该成员"});return};var until any;if in.Duration>0{until=time.Now().Add(time.Duration(in.Duration)*time.Second)};_,e=s.db.Exec(r.Context(),`UPDATE "GroupMember" SET "muteUntil"=$3,"updatedAt"=NOW() WHERE "groupId"=$1 AND "userId"=$2`,in.GroupID,in.TargetUserID,until);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"muteUntil":until})}
func (s *Server) groupDissolve(w http.ResponseWriter,r *http.Request){var in struct{GroupID,OwnerID string};if decode(r,&in)!=nil||in.GroupID==""||in.OwnerID==""{groupBad(w,"缺少必要参数");return};role,e:=groupRole(r.Context(),s,in.GroupID,in.OwnerID);if e!=nil||role!="owner"{writeJSON(w,403,map[string]string{"error":"仅群主可以解散群聊"});return};_,e=s.db.Exec(r.Context(),`DELETE FROM "Group" WHERE "id"=$1`,in.GroupID);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]bool{"ok":true})}

func (s *Server) groupQRCode(w http.ResponseWriter,r *http.Request){var in struct{GroupID,UserID string};if decode(r,&in)!=nil||in.GroupID==""||in.UserID==""{groupBad(w,"缺少必要参数");return};if _,e:=groupRole(r.Context(),s,in.GroupID,in.UserID);e!=nil{writeJSON(w,403,map[string]string{"error":"非群成员"});return};var hash string;e:=s.db.QueryRow(r.Context(),`SELECT "hash" FROM "InviteLink" WHERE "groupId"=$1 AND "name"='group_qrcode' AND "isRevoked"=false ORDER BY "createdAt" DESC LIMIT 1`,in.GroupID).Scan(&hash);if e==pgx.ErrNoRows{hash=newID();_,e=s.db.Exec(r.Context(),`INSERT INTO "InviteLink" ("id","hash","groupId","creatorId","name","maxUses","usedCount","isRevoked","createdAt","updatedAt") VALUES ($1,$2,$3,$4,'group_qrcode',0,0,false,NOW(),NOW())`,newID(),hash,in.GroupID,in.UserID)};if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"inviteLink":map[string]any{"hash":hash,"url":"/im/+"+hash,"fullUrl":groupPublicURL("/im/+"+hash),"expireAt":nil}})}

func (s *Server) groupInviteMembers(w http.ResponseWriter,r *http.Request){var in struct{GroupID,InviterID string;MemberIDs []string `json:"memberIds"`};if decode(r,&in)!=nil||in.GroupID==""||in.InviterID==""{groupBad(w,"缺少必要参数");return};if len(in.MemberIDs)>50{groupBad(w,"一次最多邀请50人");return};if _,e:=groupRole(r.Context(),s,in.GroupID,in.InviterID);e!=nil{writeJSON(w,403,map[string]string{"error":"非群成员"});return};invited:=[]string{};alreadyMembers:=[]string{};alreadyPending:=[]string{};for _,uid:=range in.MemberIDs{var member,pending bool;_=s.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM "GroupMember" WHERE "groupId"=$1 AND "userId"=$2),EXISTS(SELECT 1 FROM "GroupInvite" WHERE "groupId"=$1 AND "inviteeId"=$2 AND "status"='pending')`,in.GroupID,uid).Scan(&member,&pending);if member{alreadyMembers=append(alreadyMembers,uid);continue};if pending{alreadyPending=append(alreadyPending,uid);continue};if _,e:=s.db.Exec(r.Context(),`INSERT INTO "GroupInvite" ("id","groupId","inviterId","inviteeId","message","status","createdAt","updatedAt") VALUES ($1,$2,$3,$4,'','pending',NOW(),NOW())`,newID(),in.GroupID,in.InviterID,uid);e==nil{invited=append(invited,uid)}};var name string;_=s.db.QueryRow(r.Context(),`SELECT "name" FROM "Group" WHERE "id"=$1`,in.GroupID).Scan(&name);writeJSON(w,200,map[string]any{"ok":true,"invited":invited,"alreadyPending":alreadyPending,"alreadyMembers":alreadyMembers,"groupName":name})}
func (s *Server) groupInvites(w http.ResponseWriter,r *http.Request){uid:=groupQuery(r,"userId");if uid==""{groupBad(w,"缺少 userId");return};typ:=groupQuery(r,"type");if typ==""{typ="received"};clause:=`gi."inviteeId"=$1`;if typ=="sent"{clause=`gi."inviterId"=$1`}else if typ=="all"{clause=`(gi."inviteeId"=$1 OR gi."inviterId"=$1)`};rows,e:=s.db.Query(r.Context(),`SELECT gi."id",gi."groupId",g."name",g."avatar",g."memberCount",gi."inviterId",COALESCE(i."nickname",i."username",gi."inviterId"),COALESCE(i."avatar",''),gi."inviteeId",COALESCE(eu."nickname",eu."username",gi."inviteeId"),COALESCE(eu."avatar",''),gi."message",gi."status",gi."createdAt" FROM "GroupInvite" gi JOIN "Group" g ON g."id"=gi."groupId" LEFT JOIN "User" i ON i."id"=gi."inviterId" LEFT JOIN "User" eu ON eu."id"=gi."inviteeId" WHERE `+clause+` ORDER BY gi."createdAt" DESC`,uid);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,gid,gname,inviterName,inviteeName,msg,status string;var gav,iav,eav *string;var count int64;var inviter,invitee string;var t time.Time;if rows.Scan(&id,&gid,&gname,&gav,&count,&inviter,&inviterName,&iav,&invitee,&inviteeName,&eav,&msg,&status,&t)!=nil{continue};out=append(out,map[string]any{"id":id,"groupId":gid,"groupName":gname,"groupAvatar":gav,"groupMemberCount":count,"inviterId":inviter,"inviterName":inviterName,"inviterAvatar":iav,"inviteeId":invitee,"inviteeName":inviteeName,"inviteeAvatar":eav,"message":msg,"status":status,"timestamp":t,"isIncoming":invitee==uid})};writeJSON(w,200,map[string]any{"invites":out})}
func (s *Server) groupInviteAccept(w http.ResponseWriter,r *http.Request){id:=r.PathValue("inviteId");var in struct{UserID string};if decode(r,&in)!=nil||id==""||in.UserID==""{groupBad(w,"缺少 userId");return};var gid,invitee,status,gname string;var avatar *string;e:=s.db.QueryRow(r.Context(),`SELECT gi."groupId",gi."inviteeId",gi."status",g."name",g."avatar" FROM "GroupInvite" gi JOIN "Group" g ON g."id"=gi."groupId" WHERE gi."id"=$1`,id).Scan(&gid,&invitee,&status,&gname,&avatar);if e!=nil{writeJSON(w,404,map[string]string{"error":"群邀请不存在"});return};if invitee!=in.UserID||status!="pending"{writeJSON(w,403,map[string]string{"error":"无权处理该邀请"});return};var seq int64;_=s.db.QueryRow(r.Context(),`SELECT "lastMsgSeq" FROM "Group" WHERE "id"=$1`,gid).Scan(&seq);if _,e=s.db.Exec(r.Context(),`UPDATE "GroupInvite" SET "status"='accepted',"updatedAt"=NOW() WHERE "id"=$1`,id);e!=nil{dbError(w,e);return};if _,e=s.db.Exec(r.Context(),`INSERT INTO "GroupMember" ("id","groupId","userId","lastAckSeq","joinTime","createdAt","updatedAt") VALUES ($1,$2,$3,$4,NOW(),NOW(),NOW()) ON CONFLICT ("groupId","userId") DO NOTHING`,newID(),gid,in.UserID,seq);e!=nil{dbError(w,e);return};_,_=s.db.Exec(r.Context(),`UPDATE "Group" SET "memberCount"="memberCount"+1 WHERE "id"=$1`,gid);writeJSON(w,200,map[string]any{"ok":true,"message":"已加入群聊","groupId":gid,"groupName":gname,"groupAvatar":avatar})}
func (s *Server) groupInviteReject(w http.ResponseWriter,r *http.Request){id:=r.PathValue("inviteId");var in struct{UserID string};if decode(r,&in)!=nil||id==""||in.UserID==""{groupBad(w,"缺少 userId");return};var invitee,status string;e:=s.db.QueryRow(r.Context(),`SELECT "inviteeId","status" FROM "GroupInvite" WHERE "id"=$1`,id).Scan(&invitee,&status);if e!=nil{writeJSON(w,404,map[string]string{"error":"群邀请不存在"});return};if invitee!=in.UserID||status!="pending"{writeJSON(w,403,map[string]string{"error":"无权处理该邀请"});return};_,e=s.db.Exec(r.Context(),`UPDATE "GroupInvite" SET "status"='rejected',"updatedAt"=NOW() WHERE "id"=$1`,id);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"ok":true,"message":"已拒绝群邀请"})}
func (s *Server) groupBurnMessage(w http.ResponseWriter,r *http.Request){var in struct{MessageID,ChatID string};if decode(r,&in)!=nil||in.MessageID==""{groupBad(w,"缺少 messageId");return};_,e:=s.db.Exec(r.Context(),`UPDATE "GroupMessage" SET "isRevoked"=true,"content"='[消息已销毁]',"extra"=NULL WHERE "id"=$1`,in.MessageID);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]bool{"ok":true})}
