package api

// Phase B mirrors the authenticated friend, private-chat and presence routes
// from cqim-app/server. It deliberately keeps ciphertext opaque.

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

const (
	presenceTTL   = 90 * time.Second
	imPushChannel = "cqim:im:push"
)

func (s *Server) registerPhaseBRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/presence", s.requireUser(s.setPresence))
	mux.HandleFunc("GET /api/presence", s.requireUser(s.getPresence))
	mux.HandleFunc("POST /api/friend/request", s.requireUser(s.friendRequest))
	mux.HandleFunc("GET /api/friend/requests", s.requireUser(s.friendRequests))
	mux.HandleFunc("POST /api/friend/accept/{requestId}", s.requireUser(s.acceptFriend))
	mux.HandleFunc("POST /api/friend/reject/{requestId}", s.requireUser(s.rejectFriend))
	mux.HandleFunc("GET /api/friend/list", s.requireUser(s.friendList))
	mux.HandleFunc("DELETE /api/friend/{friendId}", s.requireUser(s.deleteFriend))
	mux.HandleFunc("GET /api/friend/check/{userId}", s.requireUser(s.checkFriend))
	mux.HandleFunc("POST /api/chat/create", s.requireUser(s.createChat))
	mux.HandleFunc("GET /api/chat/list", s.requireUser(s.chatList))
	mux.HandleFunc("POST /api/chat/send", s.requireUser(s.sendChat))
	mux.HandleFunc("GET /api/chat/{chatId}", s.requireUser(s.getChat))
	mux.HandleFunc("POST /api/chat/{chatId}/messages", s.requireUser(s.createMessage))
	mux.HandleFunc("GET /api/chat/{chatId}/messages", s.requireUser(s.messageHistory))
}

func decode(r *http.Request, dst any) error {
	if r.Body == nil { return fmt.Errorf("empty body") }
	return json.NewDecoder(http.MaxBytesReader(nil, r.Body, 1<<20)).Decode(dst)
}
func dbError(w http.ResponseWriter, err error) { writeJSON(w, 500, map[string]string{"error":"操作失败"}) }
func normalized(a,b string)(string,string) { if a < b { return a,b }; return b,a }
func newID() string { b:=make([]byte,16); if _,err:=rand.Read(b); err!=nil { return fmt.Sprintf("c%x",time.Now().UnixNano()) }; return "c"+hex.EncodeToString(b) }

func (s *Server) setPresence(w http.ResponseWriter, r *http.Request, u user) {
	var in struct{ State string `json:"state"`; ActiveChatID *string `json:"activeChatId"` }
	if err:=decode(r,&in); err!=nil || (in.State!="foreground" && in.State!="background" && in.State!="offline") { writeJSON(w,400,map[string]string{"error":"无效的在线状态"}); return }
	if s.redis==nil { writeJSON(w,500,map[string]string{"error":"在线状态服务不可用"}); return }
	ctx:=r.Context(); p,a:="user:presence:"+u.ID,"user:activeChat:"+u.ID
	var err error
	if in.State=="offline" { err=s.redis.Del(ctx,p,a).Err() } else { err=s.redis.Set(ctx,p,in.State,presenceTTL).Err(); if err==nil && in.ActiveChatID!=nil { if *in.ActiveChatID=="" { err=s.redis.Del(ctx,a).Err() } else { err=s.redis.Set(ctx,a,*in.ActiveChatID,presenceTTL).Err() } } }
	if err!=nil { writeJSON(w,500,map[string]string{"error":"更新在线状态失败"}); return }; writeJSON(w,200,map[string]any{"success":true,"redisAvailable":true})
}
func (s *Server) getPresence(w http.ResponseWriter, r *http.Request, u user) {
	state,active,available:="offline","",s.redis!=nil
	if s.redis!=nil { if v,e:=s.redis.Get(r.Context(),"user:presence:"+u.ID).Result(); e==nil && (v=="foreground"||v=="background") {state=v} else if e!=nil && e.Error()!="redis: nil" {available=false}; if v,e:=s.redis.Get(r.Context(),"user:activeChat:"+u.ID).Result(); e==nil {active=v} }
	skip:=state=="foreground" && (active=="" || r.URL.Query().Get("chatId")=="" || active==r.URL.Query().Get("chatId"))
	writeJSON(w,200,map[string]any{"state":state,"activeChatId":nilIfEmpty(active),"skipApns":skip,"redisAvailable":available})
}
func nilIfEmpty(v string) any { if v=="" {return nil}; return v }

func (s *Server) friendRequest(w http.ResponseWriter,r *http.Request,u user){
	var in struct{ToID string `json:"toId"`; Message string `json:"message"`; SearchMethod string `json:"searchMethod"`}; if decode(r,&in)!=nil||in.ToID=="" {writeJSON(w,400,map[string]string{"error":"缺少目标用户 ID"});return}; if in.ToID==u.ID {writeJSON(w,400,map[string]string{"error":"不能向自己发送好友申请"});return}; if in.SearchMethod==""{in.SearchMethod="id"}
	ctx:=r.Context(); var username,nickname string; if err:=s.db.QueryRow(ctx,`SELECT "username",COALESCE("nickname",'') FROM "User" WHERE "id"=$1`,in.ToID).Scan(&username,&nickname);err!=nil{if err==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户不存在"})}else{dbError(w,err)};return}
	a,b:=normalized(u.ID,in.ToID); var exists bool; _=s.db.QueryRow(ctx,`SELECT EXISTS(SELECT 1 FROM "Friendship" WHERE "userA"=$1 AND "userB"=$2)`,a,b).Scan(&exists);if exists{writeJSON(w,400,map[string]string{"error":"已经是好友了"});return}
	var id,from string; err:=s.db.QueryRow(ctx,`SELECT "id","fromId" FROM "FriendRequest" WHERE "status"='pending' AND (("fromId"=$1 AND "toId"=$2) OR ("fromId"=$2 AND "toId"=$1)) LIMIT 1`,u.ID,in.ToID).Scan(&id,&from);if err==nil {if from==u.ID{writeJSON(w,400,map[string]string{"error":"已发送过好友申请，等待对方处理"});return}; if err=s.acceptRequest(ctx,id,in.ToID,u.ID);err!=nil{dbError(w,err);return};writeJSON(w,200,map[string]any{"success":true,"message":"对方已向你发送申请，已自动成为好友","autoAccepted":true});return};if err!=pgx.ErrNoRows{dbError(w,err);return}
	id=newID(); now:=time.Now(); _,err=s.db.Exec(ctx,`INSERT INTO "FriendRequest" ("id","fromId","toId","message","searchMethod","status","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,'pending',$6,$6) ON CONFLICT ("fromId","toId") DO UPDATE SET "message"=EXCLUDED."message","searchMethod"=EXCLUDED."searchMethod","status"='pending',"updatedAt"=EXCLUDED."updatedAt"`,id,u.ID,in.ToID,in.Message,in.SearchMethod,now);if err!=nil{dbError(w,err);return};writeJSON(w,200,map[string]any{"success":true,"request":map[string]any{"id":id,"fromId":u.ID,"toId":in.ToID,"message":in.Message,"status":"pending","searchMethod":in.SearchMethod,"createdAt":now.UnixMilli()}})
}
func (s *Server) acceptRequest(ctx context.Context,id,from,to string) error { return pgx.BeginFunc(ctx,s.db,func(tx pgx.Tx)error{a,b:=normalized(from,to);if _,e:=tx.Exec(ctx,`UPDATE "FriendRequest" SET "status"='accepted',"updatedAt"=NOW() WHERE "id"=$1`,id);e!=nil{return e};_,e:=tx.Exec(ctx,`INSERT INTO "Friendship" ("id","userA","userB","createdAt") VALUES ($1,$2,$3,NOW()) ON CONFLICT ("userA","userB") DO NOTHING`,newID(),a,b);return e}) }
func (s *Server) friendRequests(w http.ResponseWriter,r *http.Request,u user){ typ:=r.URL.Query().Get("type");where,args:=`("toId"=$1 OR "fromId"=$1)`,[]any{u.ID};if typ=="received"{where=`"toId"=$1`}else if typ=="sent"{where=`"fromId"=$1`};rows,e:=s.db.Query(r.Context(),`SELECT f."id",f."fromId",f."toId",COALESCE(f."message",''),f."status",f."searchMethod",f."createdAt",COALESCE(fu."username",f."fromId"),COALESCE(fu."nickname",''),COALESCE(fu."avatar",''),COALESCE(tu."username",f."toId"),COALESCE(tu."nickname",''),COALESCE(tu."avatar",'') FROM "FriendRequest" f LEFT JOIN "User" fu ON fu."id"=f."fromId" LEFT JOIN "User" tu ON tu."id"=f."toId" WHERE `+where+` ORDER BY f."createdAt" DESC LIMIT 100`,args...);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]any{};for rows.Next(){var id,fr,to,msg,status,method,fu,fn,fa,tu,tn,ta string;var created time.Time;if e=rows.Scan(&id,&fr,&to,&msg,&status,&method,&created,&fu,&fn,&fa,&tu,&tn,&ta);e!=nil{dbError(w,e);return};fromName:=fn;if fromName==""{fromName=fu};toName:=tn;if toName==""{toName=tu};out=append(out,map[string]any{"id":id,"fromId":fr,"fromName":fromName,"fromUniqueId":fu,"fromAvatar":fa,"toId":to,"toName":toName,"toAvatar":ta,"message":msg,"status":status,"searchMethod":method,"timestamp":created.UnixMilli(),"isIncoming":to==u.ID})};writeJSON(w,200,map[string]any{"requests":out}) }
func (s *Server) acceptFriend(w http.ResponseWriter,r *http.Request,u user){ id:=r.PathValue("requestId");var from,to,status string;e:=s.db.QueryRow(r.Context(),`SELECT "fromId","toId","status" FROM "FriendRequest" WHERE "id"=$1`,id).Scan(&from,&to,&status);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"申请不存在"});return};if e!=nil{dbError(w,e);return};if to!=u.ID{writeJSON(w,403,map[string]string{"error":"无权操作此申请"});return};if status!="pending"{word:="拒绝";if status=="accepted"{word="接受"};writeJSON(w,400,map[string]string{"error":"申请已"+word});return};if e=s.acceptRequest(r.Context(),id,from,to);e!=nil{dbError(w,e);return};chat,e:=s.getOrCreateChat(r.Context(),from,to);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"success":true,"message":"已接受好友申请","chatId":chat.ID}) }
func (s *Server) rejectFriend(w http.ResponseWriter,r *http.Request,u user){id:=r.PathValue("requestId");var to,status string;e:=s.db.QueryRow(r.Context(),`SELECT "toId","status" FROM "FriendRequest" WHERE "id"=$1`,id).Scan(&to,&status);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"申请不存在"});return};if e!=nil{dbError(w,e);return};if to!=u.ID{writeJSON(w,403,map[string]string{"error":"无权操作此申请"});return};if status!="pending"{writeJSON(w,400,map[string]string{"error":"申请已处理"});return};_,e=s.db.Exec(r.Context(),`UPDATE "FriendRequest" SET "status"='rejected',"updatedAt"=NOW() WHERE "id"=$1`,id);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"success":true,"message":"已拒绝好友申请"})}
func (s *Server) friendList(w http.ResponseWriter,r *http.Request,u user){rows,e:=s.db.Query(r.Context(),`SELECT x."id",x."username",COALESCE(x."nickname",''),COALESCE(x."avatar",''),COALESCE(x."bio",'') FROM "Friendship" f JOIN "User" x ON x."id"=CASE WHEN f."userA"=$1 THEN f."userB" ELSE f."userA" END WHERE (f."userA"=$1 OR f."userB"=$1) AND x."isBanned"=false ORDER BY f."createdAt" DESC`,u.ID);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]any{};for rows.Next(){var id,name,nick,av,bio string;if e=rows.Scan(&id,&name,&nick,&av,&bio);e!=nil{dbError(w,e);return};n:=nick;if n==""{n=name};letter:="#";if len(n)>0&&n[0]>='A'&&n[0]<='Z'{letter=strings.ToUpper(n[:1])};online:=false;if s.redis!=nil{count,_:=s.redis.Exists(r.Context(),"user:online:"+id).Result();online=count>0};out=append(out,map[string]any{"id":id,"uniqueId":name,"name":n,"avatar":av,"bio":bio,"status":map[bool]string{true:"online",false:"offline"}[online],"letter":letter,"online":online,"devices":[]any{},"deviceLabel":nil,"lastSeen":nil})};writeJSON(w,200,map[string]any{"friends":out})}
func (s *Server) deleteFriend(w http.ResponseWriter,r *http.Request,u user){a,b:=normalized(u.ID,r.PathValue("friendId"));tag,e:=s.db.Exec(r.Context(),`DELETE FROM "Friendship" WHERE "userA"=$1 AND "userB"=$2`,a,b);if e!=nil{dbError(w,e);return};if tag.RowsAffected()==0{writeJSON(w,404,map[string]string{"error":"好友关系不存在"});return};writeJSON(w,200,map[string]any{"success":true,"message":"已删除好友"})}
func (s *Server) checkFriend(w http.ResponseWriter,r *http.Request,u user){v:=r.PathValue("userId");a,b:=normalized(u.ID,v);var f bool;_ = s.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM "Friendship" WHERE "userA"=$1 AND "userB"=$2)`,a,b).Scan(&f);var from string;e:=s.db.QueryRow(r.Context(),`SELECT "fromId" FROM "FriendRequest" WHERE "status"='pending' AND (("fromId"=$1 AND "toId"=$2) OR ("fromId"=$2 AND "toId"=$1)) LIMIT 1`,u.ID,v).Scan(&from);dir:=any(nil);if e==nil{if from==u.ID{dir="sent"}else{dir="received"}};writeJSON(w,200,map[string]any{"isFriend":f,"hasPendingRequest":e==nil,"requestDirection":dir})}

type chat struct{ID,A,B string; Last *string; LastAt *time.Time; Created time.Time}
func (s *Server) getOrCreateChat(ctx context.Context,a,b string)(chat,error){a,b=normalized(a,b);var c chat;e:=s.db.QueryRow(ctx,`SELECT "id","participantA","participantB","lastMessage","lastMessageAt","createdAt" FROM "Chat" WHERE "participantA"=$1 AND "participantB"=$2`,a,b).Scan(&c.ID,&c.A,&c.B,&c.Last,&c.LastAt,&c.Created);if e==nil{return c,nil};if e!=pgx.ErrNoRows{return c,e};now:=time.Now();c=chat{ID:newID(),A:a,B:b,Created:now};_,e=s.db.Exec(ctx,`INSERT INTO "Chat" ("id","participantA","participantB","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$4) ON CONFLICT ("participantA","participantB") DO NOTHING`,c.ID,a,b,now);if e!=nil{return c,e};return s.getOrCreateChat(ctx,a,b)}
func (s *Server) createChat(w http.ResponseWriter,r *http.Request,u user){var in struct{Target string `json:"targetUserId"`};if decode(r,&in)!=nil||in.Target==""{writeJSON(w,400,map[string]string{"error":"缺少 targetUserId"});return};if in.Target==u.ID{writeJSON(w,400,map[string]string{"error":"不能和自己创建会话"});return};var name,nick,av,bio string;e:=s.db.QueryRow(r.Context(),`SELECT "username",COALESCE("nickname",''),COALESCE("avatar",''),COALESCE("bio",'') FROM "User" WHERE "id"=$1`,in.Target).Scan(&name,&nick,&av,&bio);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户不存在"});return};if e!=nil{dbError(w,e);return};c,e:=s.getOrCreateChat(r.Context(),u.ID,in.Target);if e!=nil{dbError(w,e);return};writeJSON(w,200,map[string]any{"chat":s.chatJSON(c,u.ID,map[string]string{"id":in.Target,"username":name,"nickname":nick,"avatar":av,"bio":bio},0)})}
func (s *Server) chatJSON(c chat,me string,p map[string]string,unread int)map[string]any{n:=p["nickname"];if n==""{n=p["username"]};var lm any;if c.Last!=nil{lm=*c.Last};var la any;if c.LastAt!=nil{la=c.LastAt.UnixMilli()};return map[string]any{"id":c.ID,"participantA":c.A,"participantB":c.B,"lastMessage":lm,"lastMessageAt":la,"createdAt":c.Created.UnixMilli(),"unreadCount":unread,"peer":map[string]any{"id":p["id"],"username":p["username"],"nickname":n,"avatar":p["avatar"],"bio":p["bio"]}}}
func (s *Server) chatList(w http.ResponseWriter,r *http.Request,u user){rows,e:=s.db.Query(r.Context(),`SELECT c."id",c."participantA",c."participantB",c."lastMessage",c."lastMessageAt",c."createdAt",p."id",p."username",COALESCE(p."nickname",''),COALESCE(p."avatar",''),COALESCE(p."bio",''),(SELECT COUNT(*) FROM "PrivateMessage" m WHERE m."chatId"=c."id" AND m."senderId"<>$1 AND m."status"<>'read' AND m."isRevoked"=false) FROM "Chat" c JOIN "User" p ON p."id"=CASE WHEN c."participantA"=$1 THEN c."participantB" ELSE c."participantA" END WHERE c."participantA"=$1 OR c."participantB"=$1 ORDER BY c."lastMessageAt" DESC NULLS LAST,c."createdAt" DESC`,u.ID);if e!=nil{dbError(w,e);return};defer rows.Close();out:=[]any{};for rows.Next(){var c chat;var id,name,nick,av,bio string;var un int;if e=rows.Scan(&c.ID,&c.A,&c.B,&c.Last,&c.LastAt,&c.Created,&id,&name,&nick,&av,&bio,&un);e!=nil{dbError(w,e);return};out=append(out,s.chatJSON(c,u.ID,map[string]string{"id":id,"username":name,"nickname":nick,"avatar":av,"bio":bio},un))};writeJSON(w,200,map[string]any{"chats":out})}
func (s *Server) getChat(w http.ResponseWriter,r *http.Request,u user){c,e:=s.loadChat(r.Context(),r.PathValue("chatId"),u.ID,"无权访问此会话");if e!=nil{s.chatErr(w,e);return};peer:=c.A;if peer==u.ID{peer=c.B};var name,nick,av,bio string;e=s.db.QueryRow(r.Context(),`SELECT "username",COALESCE("nickname",''),COALESCE("avatar",''),COALESCE("bio",'') FROM "User" WHERE "id"=$1`,peer).Scan(&name,&nick,&av,&bio);if e!=nil{dbError(w,e);return};var un int;_ =s.db.QueryRow(r.Context(),`SELECT COUNT(*) FROM "PrivateMessage" WHERE "chatId"=$1 AND "senderId"<>$2 AND "status"<>'read' AND "isRevoked"=false`,c.ID,u.ID).Scan(&un);writeJSON(w,200,map[string]any{"chat":s.chatJSON(c,u.ID,map[string]string{"id":peer,"username":name,"nickname":nick,"avatar":av,"bio":bio},un)})}
func (s *Server) loadChat(ctx context.Context,id,uid,forbidden string)(chat,error){var c chat;e:=s.db.QueryRow(ctx,`SELECT "id","participantA","participantB","lastMessage","lastMessageAt","createdAt" FROM "Chat" WHERE "id"=$1`,id).Scan(&c.ID,&c.A,&c.B,&c.Last,&c.LastAt,&c.Created);if e!=nil{return c,e};if c.A!=uid&&c.B!=uid{return c,fmt.Errorf("forbidden")};return c,nil}
func (s *Server) chatErr(w http.ResponseWriter,e error){if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"会话不存在"})}else if e.Error()=="forbidden"{writeJSON(w,403,map[string]string{"error":"无权访问此会话"})}else{dbError(w,e)}}
func (s *Server) sendChat(w http.ResponseWriter,r *http.Request,u user){var in struct{ChatID,MsgType,Content string;ReplyTo *string `json:"replyTo"`};if decode(r,&in)!=nil||in.ChatID==""{writeJSON(w,400,map[string]string{"error":"缺少 chatId"});return};if in.MsgType!="encrypted"{writeJSON(w,400,map[string]string{"error":"私聊强制要求端到端加密，请发送加密消息 (msgType=encrypted)"});return};if strings.TrimSpace(in.Content)==""{writeJSON(w,400,map[string]string{"error":"加密信封内容不能为空"});return};s.persistMessage(w,r,u,in.ChatID,in.Content,in.ReplyTo,nil,0,"")}
func (s *Server) createMessage(w http.ResponseWriter,r *http.Request,u user){var in struct{Content,MsgType string;Reply *string `json:"replyToId"`;Extra json.RawMessage `json:"extra"`;Burn int `json:"burnAfterRead"`;HMAC string `json:"hmac"`};if decode(r,&in)!=nil{writeJSON(w,400,map[string]string{"error":"请求无效"});return};if in.MsgType!="encrypted"{writeJSON(w,400,map[string]string{"error":"私聊强制要求端到端加密，请发送加密消息"});return};if in.Content==""{writeJSON(w,400,map[string]string{"error":"加密信封不能为空"});return};valid:=map[int]bool{5:true,10:true,30:true,60:true,300:true,3600:true,86400:true,604800:true};burn:=0;if valid[in.Burn]{burn=in.Burn};var extra any;if len(in.Extra)>0&&string(in.Extra)!="null"{if json.Unmarshal(in.Extra,&extra)!=nil{extra=nil}};s.persistMessage(w,r,u,r.PathValue("chatId"),in.Content,in.Reply,extra,burn,in.HMAC)}
func (s *Server) persistMessage(w http.ResponseWriter,r *http.Request,u user,chatID,content string,reply *string,extra any,burn int,hmac string){c,e:=s.loadChat(r.Context(),chatID,u.ID,"无权发送消息");if e!=nil{if e.Error()=="forbidden"{writeJSON(w,403,map[string]string{"error":"无权发送消息"})}else{s.chatErr(w,e)};return};var extraText *string;if extra!=nil{b,_:=json.Marshal(extra);v:=string(b);extraText=&v};if len(hmac)!=64{hmac=""};now:=time.Now();id:=newID();_,e=s.db.Exec(r.Context(),`INSERT INTO "PrivateMessage" ("id","chatId","senderId","msgType","content","replyToId","extra","status","burnAfterRead","hmac","createdAt") VALUES ($1,$2,$3,'encrypted',$4,$5,$6,'sent',NULLIF($7,0),NULLIF($8,''),$9)`,id,chatID,u.ID,content,reply,extraText,burn,hmac,now);if e!=nil{dbError(w,e);return};_,e=s.db.Exec(r.Context(),`UPDATE "Chat" SET "lastMessage"='🔒 [加密消息]',"lastMessageAt"=$2,"updatedAt"=$2 WHERE "id"=$1`,chatID,now);if e!=nil{dbError(w,e);return};result:=map[string]any{"id":id,"chatId":chatID,"senderId":u.ID,"msgType":"encrypted","content":content,"replyToId":reply,"isRevoked":false,"status":"sent","extra":extra,"createdAt":now.UnixMilli()};if burn>0{result["burnAfterRead"]=burn};if hmac!=""{result["hmac"]=hmac};peer:=c.A;if peer==u.ID{peer=c.B};s.notify(r.Context(),peer,chatID,result);writeJSON(w,200,map[string]any{"message":result})}
func (s *Server) notify(ctx context.Context,peer,chatID string,msg map[string]any){if s.redis==nil{return};_ =s.redis.HIncrBy(ctx,"unread:"+peer,chatID,1).Err();_ =s.redis.Del(ctx,"conv:list:"+peer,"conv:list:"+fmt.Sprint(msg["senderId"])).Err();payload:=map[string]any{"type":"private_message","payload":msg};b,_:=json.Marshal(map[string]any{"userId":peer,"payload":payload});_ =s.redis.Publish(ctx,imPushChannel,b).Err()}
func (s *Server) messageHistory(w http.ResponseWriter,r *http.Request,u user){_,e:=s.loadChat(r.Context(),r.PathValue("chatId"),u.ID,"无权访问此会话");if e!=nil{s.chatErr(w,e);return};limit:=50;if n,e:=strconv.Atoi(r.URL.Query().Get("limit"));e==nil&&n>0{limit=n};if limit>100{limit=100};before:=r.URL.Query().Get("before");args:=[]any{r.PathValue("chatId")};where:=`"chatId"=$1`;if before!=""{var t time.Time;if e=s.db.QueryRow(r.Context(),`SELECT "createdAt" FROM "PrivateMessage" WHERE "id"=$1`,before).Scan(&t);e==nil{args=append(args,t);where+=fmt.Sprintf(` AND "createdAt"<$%d`,len(args))}};args=append(args,limit+1);rows,e:=s.db.Query(r.Context(),`SELECT "id","chatId","senderId","msgType","content","replyToId","isRevoked","status","extra","createdAt","burnAfterRead","burnReadAt","hmac" FROM "PrivateMessage" WHERE `+where+fmt.Sprintf(` ORDER BY "createdAt" DESC LIMIT $%d`,len(args)),args...);if e!=nil{dbError(w,e);return};defer rows.Close();all:=[]map[string]any{};for rows.Next(){var id,cid,sid,typ,content,status string;var reply,extra,hmac *string;var revoked bool;var created time.Time;var burn *int;var readAt *time.Time;if e=rows.Scan(&id,&cid,&sid,&typ,&content,&reply,&revoked,&status,&extra,&created,&burn,&readAt,&hmac);e!=nil{dbError(w,e);return};m:=map[string]any{"id":id,"chatId":cid,"senderId":sid,"msgType":typ,"content":content,"replyToId":reply,"isRevoked":revoked,"status":status,"createdAt":created.UnixMilli()};if revoked{m["content"]="消息已撤回"}else if extra!=nil{var x any;if json.Unmarshal([]byte(*extra),&x)==nil{m["extra"]=x}};if burn!=nil{m["burnAfterRead"]=*burn;m["burnReadAt"]=nil;if readAt!=nil{m["burnReadAt"]=readAt.UnixMilli()}};if hmac!=nil{m["hmac"]=*hmac};all=append(all,m)};more:=len(all)>limit;if more{all=all[:limit]};for i,j:=0,len(all)-1;i<j;i,j=i+1,j-1{all[i],all[j]=all[j],all[i]};writeJSON(w,200,map[string]any{"messages":all,"hasMore":more})}
