package api

import (
 "context"
 "net/http"
 "strings"
 "time"
 "github.com/jackc/pgx/v5"
)

type publicUser struct { ID string `json:"id"`; Username string `json:"username"`; Nickname string `json:"nickname"`; Avatar string `json:"avatar"`; Bio string `json:"bio"`; BackgroundURL string `json:"backgroundUrl,omitempty"`; Online bool `json:"online"` }
func displayName(nickname,username,id string) string { if nickname!="" {return nickname};if username!="" {return username};return id }
func publicAvatar(raw string) string { raw=strings.TrimSpace(raw);if raw==""{return ""};if strings.HasPrefix(raw,"https://"){return raw};if strings.HasPrefix(raw,"/api/media/")||strings.HasPrefix(raw,"/"){return raw};return "/api/media/"+raw }
func (s *Server) userOnline(ctx context.Context,id string) bool { if s.redis==nil{return false};n,e:=s.redis.Exists(ctx,"online:"+id,"user:presence:"+id).Result();return e==nil&&n>0 }
func builtinUser(id string)(map[string]any,bool){if id=="official"{return map[string]any{"id":"official","username":"admin","nickname":"imim 官方","avatar":"/imim-official-avatar.jpg","bio":"imim 官方账号","online":true,"lastSeen":nil,"devices":[]map[string]string{{"deviceType":"server","browser":"System","os":"imim Cloud"}}},true};if id=="BOT"{return map[string]any{"id":"BOT","username":"BOT","nickname":"imim AI","avatar":"/imim-ai-avatar.jpg","bio":"imim AI 助手","online":true,"lastSeen":nil,"devices":[]map[string]string{{"deviceType":"server","browser":"AI Runtime","os":"imim Cloud"}}},true};return nil,false}
func (s *Server) loadPublicUser(ctx context.Context,id string)(publicUser,error){var u publicUser;var nickname,avatar,bio,bg *string;err:=s.db.QueryRow(ctx,`SELECT "id","username","nickname","avatar","bio","backgroundUrl" FROM "User" WHERE "id"=$1`,id).Scan(&u.ID,&u.Username,&nickname,&avatar,&bio,&bg);if err!=nil{return u,err};if nickname!=nil{u.Nickname=*nickname};if avatar!=nil{u.Avatar=publicAvatar(*avatar)};if bio!=nil{u.Bio=*bio};if bg!=nil{u.BackgroundURL=*bg};u.Nickname=displayName(u.Nickname,u.Username,u.ID);u.Online=s.userOnline(ctx,u.ID);return u,nil}
func (s *Server) usersSearch(w http.ResponseWriter,r *http.Request){q:=strings.TrimSpace(r.URL.Query().Get("q"));if q==""{writeJSON(w,400,map[string]string{"error":"请输入至少1个字符"});return};rows,e:=s.db.Query(r.Context(),`SELECT "id","username",COALESCE("nickname",''),COALESCE("avatar",''),COALESCE("bio",'') FROM "User" WHERE "isBanned"=false AND ("id"=$1 OR "username"=$1 OR "phone"=$1 OR "email"=$1) LIMIT 10`,q);if e!=nil{writeJSON(w,500,map[string]string{"error":"搜索失败"});return};defer rows.Close();users:=[]map[string]any{};for rows.Next(){var id,name,nick,av,bio string;if rows.Scan(&id,&name,&nick,&av,&bio)==nil{users=append(users,map[string]any{"id":id,"username":name,"nickname":displayName(nick,name,id),"avatar":publicAvatar(av),"bio":bio})}};writeJSON(w,200,map[string]any{"users":users})}
func (s *Server) userPublic(w http.ResponseWriter,r *http.Request){id:=r.PathValue("userId");if b,ok:=builtinUser(id);ok{writeJSON(w,200,b);return};u,e:=s.loadPublicUser(r.Context(),id);if e==pgx.ErrNoRows{writeJSON(w,404,map[string]string{"error":"用户不存在"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"服务器错误"});return};writeJSON(w,200,map[string]any{"id":u.ID,"username":u.Username,"nickname":u.Nickname,"avatar":u.Avatar,"bio":u.Bio,"backgroundUrl":u.BackgroundURL,"online":u.Online,"lastSeen":nil,"devices":[]any{}})}
func (s *Server) userPresence(w http.ResponseWriter,r *http.Request){id:=r.PathValue("userId");if b,ok:=builtinUser(id);ok{writeJSON(w,200,map[string]any{"userId":id,"online":true,"lastSeen":nil,"devices":b["devices"]});return};writeJSON(w,200,map[string]any{"userId":id,"online":s.userOnline(r.Context(),id),"lastSeen":nil,"devices":[]any{}})}
func (s *Server) userMe(w http.ResponseWriter,_ *http.Request,u user){nick:="";if u.Nickname!=nil{nick=*u.Nickname};av:="";if u.Avatar!=nil{av=publicAvatar(*u.Avatar)};bio:="";if u.Bio!=nil{bio=*u.Bio};writeJSON(w,200,map[string]any{"id":u.ID,"username":u.Username,"nickname":displayName(nick,u.Username,u.ID),"avatar":av,"bio":bio,"online":s.userOnline(context.Background(),u.ID),"displayName":displayName(nick,u.Username,u.ID),"uniqueId":func()string{if u.Username!=""{return u.Username};return u.ID}()})}
func (s *Server) profile(w http.ResponseWriter,r *http.Request){key:=r.URL.Query().Get("userId");if key==""||key=="me"{token:=bearerToken(r.Header.Get("Authorization"));if token!=""{if u,e:=s.findSessionUser(r.Context(),token);e==nil{key=u.ID}}};if key==""||key=="me"{writeJSON(w,200,map[string]any{"profile":map[string]any{"id":"me","username":"me","name":"me","nickname":"me","gender":"","region":"","phone":"","email":"","wechatId":"me","bio":"","avatar":"","backgroundUrl":"","birthday":""}});return};var id,name,nick,av,bg,bio,phone,email,gender,region,birthday string;e:=s.db.QueryRow(r.Context(),`SELECT "id","username",COALESCE("nickname",''),COALESCE("avatar",''),COALESCE("backgroundUrl",''),COALESCE("bio",''),COALESCE("phone",''),COALESCE("email",''),COALESCE("gender",''),COALESCE("region",''),COALESCE("birthday",'') FROM "User" WHERE "id"=$1 OR "username"=$1 LIMIT 1`,key).Scan(&id,&name,&nick,&av,&bg,&bio,&phone,&email,&gender,&region,&birthday);if e==pgx.ErrNoRows{writeJSON(w,200,map[string]any{"profile":map[string]any{"id":key,"username":key,"name":key,"nickname":key,"gender":"","region":"","phone":"","email":"","wechatId":key,"bio":"","avatar":"","backgroundUrl":"","birthday":""}});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"服务器错误"});return};display:=displayName(nick,name,id);writeJSON(w,200,map[string]any{"profile":map[string]any{"id":id,"username":name,"name":display,"nickname":display,"gender":gender,"region":region,"phone":phone,"email":email,"wechatId":name,"bio":bio,"avatar":publicAvatar(av),"backgroundUrl":bg,"birthday":birthday,"online":s.userOnline(r.Context(),id),"uniqueId":name}})}
var _ = time.Second
