// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: neomsg/v1/envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MSG_TYPE_TEXT        MessageType = 1
	MessageType_MSG_TYPE_IMAGE       MessageType = 2
	MessageType_MSG_TYPE_VIDEO       MessageType = 3
	MessageType_MSG_TYPE_AUDIO       MessageType = 4
	MessageType_MSG_TYPE_FILE        MessageType = 5
	MessageType_MSG_TYPE_STICKER     MessageType = 6
	MessageType_MSG_TYPE_LOCATION    MessageType = 7
	MessageType_MSG_TYPE_CONTACT     MessageType = 8
	MessageType_MSG_TYPE_SYSTEM      MessageType = 9
	MessageType_MSG_TYPE_ENCRYPTED   MessageType = 10 // Secret Chat 密文
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MSG_TYPE_UNSPECIFIED",
		1:  "MSG_TYPE_TEXT",
		2:  "MSG_TYPE_IMAGE",
		3:  "MSG_TYPE_VIDEO",
		4:  "MSG_TYPE_AUDIO",
		5:  "MSG_TYPE_FILE",
		6:  "MSG_TYPE_STICKER",
		7:  "MSG_TYPE_LOCATION",
		8:  "MSG_TYPE_CONTACT",
		9:  "MSG_TYPE_SYSTEM",
		10: "MSG_TYPE_ENCRYPTED",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED": 0,
		"MSG_TYPE_TEXT":        1,
		"MSG_TYPE_IMAGE":       2,
		"MSG_TYPE_VIDEO":       3,
		"MSG_TYPE_AUDIO":       4,
		"MSG_TYPE_FILE":        5,
		"MSG_TYPE_STICKER":     6,
		"MSG_TYPE_LOCATION":    7,
		"MSG_TYPE_CONTACT":     8,
		"MSG_TYPE_SYSTEM":      9,
		"MSG_TYPE_ENCRYPTED":   10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_neomsg_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_neomsg_v1_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope — 所有客户端-服务器通信的统一包装层
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Seq       int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Pts       int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"` // 持久化时间戳序列（同步用）
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_AuthRequest
	//	*Envelope_SendMessage
	//	*Envelope_AckRead
	//	*Envelope_Typing
	//	*Envelope_Ping
	//	*Envelope_GetDifference
	//	*Envelope_UploadPart
	//	*Envelope_WireMessage
	//	*Envelope_SyncRequest
	//	*Envelope_AuthResponse
	//	*Envelope_NewMessage
	//	*Envelope_ReadReceipt
	//	*Envelope_TypingEvent
	//	*Envelope_Pong
	//	*Envelope_Updates
	//	*Envelope_UploadPartAck
	//	*Envelope_MessageAck
	//	*Envelope_SyncResponse
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *Envelope) GetSendMessage() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *Envelope) GetAckRead() *AckReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AckRead); ok {
			return x.AckRead
		}
	}
	return nil
}

func (x *Envelope) GetTyping() *TypingRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *Envelope) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetGetDifference() *GetDifferenceRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetDifference); ok {
			return x.GetDifference
		}
	}
	return nil
}

func (x *Envelope) GetUploadPart() *UploadPartRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UploadPart); ok {
			return x.UploadPart
		}
	}
	return nil
}

func (x *Envelope) GetWireMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WireMessage); ok {
			return x.WireMessage
		}
	}
	return nil
}

func (x *Envelope) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Envelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Envelope) GetNewMessage() *NewMessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *Envelope) GetReadReceipt() *ReadReceiptEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

func (x *Envelope) GetTypingEvent() *TypingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TypingEvent); ok {
			return x.TypingEvent
		}
	}
	return nil
}

func (x *Envelope) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetUpdates() *UpdatesEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Updates); ok {
			return x.Updates
		}
	}
	return nil
}

func (x *Envelope) GetUploadPartAck() *UploadPartResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UploadPartAck); ok {
			return x.UploadPartAck
		}
	}
	return nil
}

func (x *Envelope) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *Envelope) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_AuthRequest struct {
	// Client → Server
	AuthRequest *AuthRequest `protobuf:"bytes,10,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type Envelope_SendMessage struct {
	SendMessage *SendMessageRequest `protobuf:"bytes,11,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type Envelope_AckRead struct {
	AckRead *AckReadRequest `protobuf:"bytes,12,opt,name=ack_read,json=ackRead,proto3,oneof"`
}

type Envelope_Typing struct {
	Typing *TypingRequest `protobuf:"bytes,13,opt,name=typing,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *PingRequest `protobuf:"bytes,14,opt,name=ping,proto3,oneof"`
}

type Envelope_GetDifference struct {
	GetDifference *GetDifferenceRequest `protobuf:"bytes,15,opt,name=get_difference,json=getDifference,proto3,oneof"`
}

type Envelope_UploadPart struct {
	UploadPart *UploadPartRequest `protobuf:"bytes,16,opt,name=upload_part,json=uploadPart,proto3,oneof"`
}

type Envelope_WireMessage struct {
	WireMessage *Message `protobuf:"bytes,17,opt,name=wire_message,json=wireMessage,proto3,oneof"`
}

type Envelope_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,18,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Envelope_AuthResponse struct {
	// Server → Client
	AuthResponse *AuthResponse `protobuf:"bytes,20,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type Envelope_NewMessage struct {
	NewMessage *NewMessageEvent `protobuf:"bytes,21,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type Envelope_ReadReceipt struct {
	ReadReceipt *ReadReceiptEvent `protobuf:"bytes,22,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

type Envelope_TypingEvent struct {
	TypingEvent *TypingEvent `protobuf:"bytes,23,opt,name=typing_event,json=typingEvent,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *PongResponse `protobuf:"bytes,24,opt,name=pong,proto3,oneof"`
}

type Envelope_Updates struct {
	Updates *UpdatesEvent `protobuf:"bytes,25,opt,name=updates,proto3,oneof"`
}

type Envelope_UploadPartAck struct {
	UploadPartAck *UploadPartResponse `protobuf:"bytes,26,opt,name=upload_part_ack,json=uploadPartAck,proto3,oneof"`
}

type Envelope_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,27,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type Envelope_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,28,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ErrorResponse `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*Envelope_AuthRequest) isEnvelope_Payload() {}

func (*Envelope_SendMessage) isEnvelope_Payload() {}

func (*Envelope_AckRead) isEnvelope_Payload() {}

func (*Envelope_Typing) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_GetDifference) isEnvelope_Payload() {}

func (*Envelope_UploadPart) isEnvelope_Payload() {}

func (*Envelope_WireMessage) isEnvelope_Payload() {}

func (*Envelope_SyncRequest) isEnvelope_Payload() {}

func (*Envelope_AuthResponse) isEnvelope_Payload() {}

func (*Envelope_NewMessage) isEnvelope_Payload() {}

func (*Envelope_ReadReceipt) isEnvelope_Payload() {}

func (*Envelope_TypingEvent) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Updates) isEnvelope_Payload() {}

func (*Envelope_UploadPartAck) isEnvelope_Payload() {}

func (*Envelope_MessageAck) isEnvelope_Payload() {}

func (*Envelope_SyncResponse) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"` // ios | android | web
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *AuthRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pts           int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`
	ServerTime    int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *AuthResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int64                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	MsgType       MessageType            `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=neomsg.v1.MessageType" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 文本 UTF-8 或密文
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ReplyToId     int64                  `protobuf:"varint,5,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"`
	Media         *MediaRef              `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 自毁消息（0=不自毁）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *SendMessageRequest) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MSG_TYPE_UNSPECIFIED
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetReplyToId() int64 {
	if x != nil {
		return x.ReplyToId
	}
	return 0
}

func (x *SendMessageRequest) GetMedia() *MediaRef {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *SendMessageRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type NewMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DialogId      int64                  `protobuf:"varint,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       MessageType            `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3,enum=neomsg.v1.MessageType" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ServerTime    int64                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Seq           int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Media         *MediaRef              `protobuf:"bytes,8,opt,name=media,proto3" json:"media,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,9,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageEvent) Reset() {
	*x = NewMessageEvent{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageEvent) ProtoMessage() {}

func (x *NewMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageEvent.ProtoReflect.Descriptor instead.
func (*NewMessageEvent) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *NewMessageEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NewMessageEvent) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *NewMessageEvent) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NewMessageEvent) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MSG_TYPE_UNSPECIFIED
}

func (x *NewMessageEvent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *NewMessageEvent) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *NewMessageEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NewMessageEvent) GetMedia() *MediaRef {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *NewMessageEvent) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type MediaRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"` // 音视频秒数
	Thumbnail     string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRef) Reset() {
	*x = MediaRef{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRef) ProtoMessage() {}

func (x *MediaRef) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRef.ProtoReflect.Descriptor instead.
func (*MediaRef) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *MediaRef) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MediaRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaRef) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MediaRef) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type AckReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int64                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	LastReadId    int64                  `protobuf:"varint,2,opt,name=last_read_id,json=lastReadId,proto3" json:"last_read_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReadRequest) Reset() {
	*x = AckReadRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReadRequest) ProtoMessage() {}

func (x *AckReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReadRequest.ProtoReflect.Descriptor instead.
func (*AckReadRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *AckReadRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *AckReadRequest) GetLastReadId() int64 {
	if x != nil {
		return x.LastReadId
	}
	return 0
}

type ReadReceiptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int64                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	ReaderId      int64                  `protobuf:"varint,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`
	LastReadId    int64                  `protobuf:"varint,3,opt,name=last_read_id,json=lastReadId,proto3" json:"last_read_id,omitempty"`
	ReadTime      int64                  `protobuf:"varint,4,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceiptEvent) Reset() {
	*x = ReadReceiptEvent{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptEvent) ProtoMessage() {}

func (x *ReadReceiptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptEvent.ProtoReflect.Descriptor instead.
func (*ReadReceiptEvent) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *ReadReceiptEvent) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *ReadReceiptEvent) GetReaderId() int64 {
	if x != nil {
		return x.ReaderId
	}
	return 0
}

func (x *ReadReceiptEvent) GetLastReadId() int64 {
	if x != nil {
		return x.LastReadId
	}
	return 0
}

func (x *ReadReceiptEvent) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

type TypingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int64                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingRequest) Reset() {
	*x = TypingRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRequest) ProtoMessage() {}

func (x *TypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingRequest.ProtoReflect.Descriptor instead.
func (*TypingRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *TypingRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *TypingRequest) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int64                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{9}
}

func (x *TypingEvent) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *TypingEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TypingEvent) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{10}
}

func (x *PingRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{11}
}

func (x *PongResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type GetDifferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPts       int64                  `protobuf:"varint,1,opt,name=from_pts,json=fromPts,proto3" json:"from_pts,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDifferenceRequest) Reset() {
	*x = GetDifferenceRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDifferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDifferenceRequest) ProtoMessage() {}

func (x *GetDifferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDifferenceRequest.ProtoReflect.Descriptor instead.
func (*GetDifferenceRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{12}
}

func (x *GetDifferenceRequest) GetFromPts() int64 {
	if x != nil {
		return x.FromPts
	}
	return 0
}

func (x *GetDifferenceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdatesEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pts           int64                  `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	Updates       []*Update              `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatesEvent) Reset() {
	*x = UpdatesEvent{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatesEvent) ProtoMessage() {}

func (x *UpdatesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatesEvent.ProtoReflect.Descriptor instead.
func (*UpdatesEvent) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatesEvent) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *UpdatesEvent) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Update_NewMessage
	//	*Update_ReadReceipt
	Data          isUpdate_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{14}
}

func (x *Update) GetData() isUpdate_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Update) GetNewMessage() *NewMessageEvent {
	if x != nil {
		if x, ok := x.Data.(*Update_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *Update) GetReadReceipt() *ReadReceiptEvent {
	if x != nil {
		if x, ok := x.Data.(*Update_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

type isUpdate_Data interface {
	isUpdate_Data()
}

type Update_NewMessage struct {
	NewMessage *NewMessageEvent `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type Update_ReadReceipt struct {
	ReadReceipt *ReadReceiptEvent `protobuf:"bytes,2,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

func (*Update_NewMessage) isUpdate_Data() {}

func (*Update_ReadReceipt) isUpdate_Data() {}

type UploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartIndex     int32                  `protobuf:"varint,2,opt,name=part_index,json=partIndex,proto3" json:"part_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{15}
}

func (x *UploadPartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartRequest) GetPartIndex() int32 {
	if x != nil {
		return x.PartIndex
	}
	return 0
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPartRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type UploadPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartResponse) Reset() {
	*x = UploadPartResponse{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartResponse) ProtoMessage() {}

func (x *UploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartResponse.ProtoReflect.Descriptor instead.
func (*UploadPartResponse) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{16}
}

func (x *UploadPartResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadPartResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_neomsg_v1_envelope_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_envelope_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_envelope_proto_rawDescGZIP(), []int{17}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_neomsg_v1_envelope_proto protoreflect.FileDescriptor

const file_neomsg_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18neomsg/v1/envelope.proto\x12\tneomsg.v1\x1a\x14neomsg/v1/wire.proto\"\xcb\t\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x12;\n" +
	"\fauth_request\x18\n" +
	" \x01(\v2\x16.neomsg.v1.AuthRequestH\x00R\vauthRequest\x12B\n" +
	"\fsend_message\x18\v \x01(\v2\x1d.neomsg.v1.SendMessageRequestH\x00R\vsendMessage\x126\n" +
	"\back_read\x18\f \x01(\v2\x19.neomsg.v1.AckReadRequestH\x00R\aackRead\x122\n" +
	"\x06typing\x18\r \x01(\v2\x18.neomsg.v1.TypingRequestH\x00R\x06typing\x12,\n" +
	"\x04ping\x18\x0e \x01(\v2\x16.neomsg.v1.PingRequestH\x00R\x04ping\x12H\n" +
	"\x0eget_difference\x18\x0f \x01(\v2\x1f.neomsg.v1.GetDifferenceRequestH\x00R\rgetDifference\x12?\n" +
	"\vupload_part\x18\x10 \x01(\v2\x1c.neomsg.v1.UploadPartRequestH\x00R\n" +
	"uploadPart\x127\n" +
	"\fwire_message\x18\x11 \x01(\v2\x12.neomsg.v1.MessageH\x00R\vwireMessage\x12;\n" +
	"\fsync_request\x18\x12 \x01(\v2\x16.neomsg.v1.SyncRequestH\x00R\vsyncRequest\x12>\n" +
	"\rauth_response\x18\x14 \x01(\v2\x17.neomsg.v1.AuthResponseH\x00R\fauthResponse\x12=\n" +
	"\vnew_message\x18\x15 \x01(\v2\x1a.neomsg.v1.NewMessageEventH\x00R\n" +
	"newMessage\x12@\n" +
	"\fread_receipt\x18\x16 \x01(\v2\x1b.neomsg.v1.ReadReceiptEventH\x00R\vreadReceipt\x12;\n" +
	"\ftyping_event\x18\x17 \x01(\v2\x16.neomsg.v1.TypingEventH\x00R\vtypingEvent\x12-\n" +
	"\x04pong\x18\x18 \x01(\v2\x17.neomsg.v1.PongResponseH\x00R\x04pong\x123\n" +
	"\aupdates\x18\x19 \x01(\v2\x17.neomsg.v1.UpdatesEventH\x00R\aupdates\x12G\n" +
	"\x0fupload_part_ack\x18\x1a \x01(\v2\x1d.neomsg.v1.UploadPartResponseH\x00R\ruploadPartAck\x128\n" +
	"\vmessage_ack\x18\x1b \x01(\v2\x15.neomsg.v1.MessageAckH\x00R\n" +
	"messageAck\x12>\n" +
	"\rsync_response\x18\x1c \x01(\v2\x17.neomsg.v1.SyncResponseH\x00R\fsyncResponse\x120\n" +
	"\x05error\x18c \x01(\v2\x18.neomsg.v1.ErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"\x8a\x01\n" +
	"\vAuthRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x89\x01\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\x8e\x02\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x03R\bdialogId\x121\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x16.neomsg.v1.MessageTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\x12\x1e\n" +
	"\vreply_to_id\x18\x05 \x01(\x03R\treplyToId\x12)\n" +
	"\x05media\x18\x06 \x01(\v2\x13.neomsg.v1.MediaRefR\x05media\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x05R\n" +
	"ttlSeconds\"\xb6\x02\n" +
	"\x0fNewMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\x03R\bdialogId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x121\n" +
	"\bmsg_type\x18\x04 \x01(\x0e2\x16.neomsg.v1.MessageTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x03R\n" +
	"serverTime\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12)\n" +
	"\x05media\x18\b \x01(\v2\x13.neomsg.v1.MediaRefR\x05media\x12\x1f\n" +
	"\vttl_seconds\x18\t \x01(\x05R\n" +
	"ttlSeconds\"\xbc\x01\n" +
	"\bMediaRef\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail\"O\n" +
	"\x0eAckReadRequest\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x03R\bdialogId\x12 \n" +
	"\flast_read_id\x18\x02 \x01(\x03R\n" +
	"lastReadId\"\x8b\x01\n" +
	"\x10ReadReceiptEvent\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x03R\bdialogId\x12\x1b\n" +
	"\treader_id\x18\x02 \x01(\x03R\breaderId\x12 \n" +
	"\flast_read_id\x18\x03 \x01(\x03R\n" +
	"lastReadId\x12\x1b\n" +
	"\tread_time\x18\x04 \x01(\x03R\breadTime\"I\n" +
	"\rTypingRequest\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x03R\bdialogId\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\"`\n" +
	"\vTypingEvent\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x03R\bdialogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tis_typing\x18\x03 \x01(\bR\bisTyping\".\n" +
	"\vPingRequest\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"/\n" +
	"\fPongResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"G\n" +
	"\x14GetDifferenceRequest\x12\x19\n" +
	"\bfrom_pts\x18\x01 \x01(\x03R\afromPts\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\fUpdatesEvent\x12\x10\n" +
	"\x03pts\x18\x01 \x01(\x03R\x03pts\x12+\n" +
	"\aupdates\x18\x02 \x03(\v2\x11.neomsg.v1.UpdateR\aupdates\"\x91\x01\n" +
	"\x06Update\x12=\n" +
	"\vnew_message\x18\x01 \x01(\v2\x1a.neomsg.v1.NewMessageEventH\x00R\n" +
	"newMessage\x12@\n" +
	"\fread_receipt\x18\x02 \x01(\v2\x1b.neomsg.v1.ReadReceiptEventH\x00R\vreadReceiptB\x06\n" +
	"\x04data\"|\n" +
	"\x11UploadPartRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1d\n" +
	"\n" +
	"part_index\x18\x02 \x01(\x05R\tpartIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"f\n" +
	"\x12UploadPartResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\"\\\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId*\xf9\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eMSG_TYPE_IMAGE\x10\x02\x12\x12\n" +
	"\x0eMSG_TYPE_VIDEO\x10\x03\x12\x12\n" +
	"\x0eMSG_TYPE_AUDIO\x10\x04\x12\x11\n" +
	"\rMSG_TYPE_FILE\x10\x05\x12\x14\n" +
	"\x10MSG_TYPE_STICKER\x10\x06\x12\x15\n" +
	"\x11MSG_TYPE_LOCATION\x10\a\x12\x14\n" +
	"\x10MSG_TYPE_CONTACT\x10\b\x12\x13\n" +
	"\x0fMSG_TYPE_SYSTEM\x10\t\x12\x16\n" +
	"\x12MSG_TYPE_ENCRYPTED\x10\n" +
	"B:Z8github.com/neomsg/neomsg/backend/internal/protocol/pb;pbb\x06proto3"

var (
	file_neomsg_v1_envelope_proto_rawDescOnce sync.Once
	file_neomsg_v1_envelope_proto_rawDescData []byte
)

func file_neomsg_v1_envelope_proto_rawDescGZIP() []byte {
	file_neomsg_v1_envelope_proto_rawDescOnce.Do(func() {
		file_neomsg_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neomsg_v1_envelope_proto_rawDesc), len(file_neomsg_v1_envelope_proto_rawDesc)))
	})
	return file_neomsg_v1_envelope_proto_rawDescData
}

var file_neomsg_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neomsg_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_neomsg_v1_envelope_proto_goTypes = []any{
	(MessageType)(0),             // 0: neomsg.v1.MessageType
	(*Envelope)(nil),             // 1: neomsg.v1.Envelope
	(*AuthRequest)(nil),          // 2: neomsg.v1.AuthRequest
	(*AuthResponse)(nil),         // 3: neomsg.v1.AuthResponse
	(*SendMessageRequest)(nil),   // 4: neomsg.v1.SendMessageRequest
	(*NewMessageEvent)(nil),      // 5: neomsg.v1.NewMessageEvent
	(*MediaRef)(nil),             // 6: neomsg.v1.MediaRef
	(*AckReadRequest)(nil),       // 7: neomsg.v1.AckReadRequest
	(*ReadReceiptEvent)(nil),     // 8: neomsg.v1.ReadReceiptEvent
	(*TypingRequest)(nil),        // 9: neomsg.v1.TypingRequest
	(*TypingEvent)(nil),          // 10: neomsg.v1.TypingEvent
	(*PingRequest)(nil),          // 11: neomsg.v1.PingRequest
	(*PongResponse)(nil),         // 12: neomsg.v1.PongResponse
	(*GetDifferenceRequest)(nil), // 13: neomsg.v1.GetDifferenceRequest
	(*UpdatesEvent)(nil),         // 14: neomsg.v1.UpdatesEvent
	(*Update)(nil),               // 15: neomsg.v1.Update
	(*UploadPartRequest)(nil),    // 16: neomsg.v1.UploadPartRequest
	(*UploadPartResponse)(nil),   // 17: neomsg.v1.UploadPartResponse
	(*ErrorResponse)(nil),        // 18: neomsg.v1.ErrorResponse
	(*Message)(nil),              // 19: neomsg.v1.Message
	(*SyncRequest)(nil),          // 20: neomsg.v1.SyncRequest
	(*MessageAck)(nil),           // 21: neomsg.v1.MessageAck
	(*SyncResponse)(nil),         // 22: neomsg.v1.SyncResponse
}
var file_neomsg_v1_envelope_proto_depIdxs = []int32{
	2,  // 0: neomsg.v1.Envelope.auth_request:type_name -> neomsg.v1.AuthRequest
	4,  // 1: neomsg.v1.Envelope.send_message:type_name -> neomsg.v1.SendMessageRequest
	7,  // 2: neomsg.v1.Envelope.ack_read:type_name -> neomsg.v1.AckReadRequest
	9,  // 3: neomsg.v1.Envelope.typing:type_name -> neomsg.v1.TypingRequest
	11, // 4: neomsg.v1.Envelope.ping:type_name -> neomsg.v1.PingRequest
	13, // 5: neomsg.v1.Envelope.get_difference:type_name -> neomsg.v1.GetDifferenceRequest
	16, // 6: neomsg.v1.Envelope.upload_part:type_name -> neomsg.v1.UploadPartRequest
	19, // 7: neomsg.v1.Envelope.wire_message:type_name -> neomsg.v1.Message
	20, // 8: neomsg.v1.Envelope.sync_request:type_name -> neomsg.v1.SyncRequest
	3,  // 9: neomsg.v1.Envelope.auth_response:type_name -> neomsg.v1.AuthResponse
	5,  // 10: neomsg.v1.Envelope.new_message:type_name -> neomsg.v1.NewMessageEvent
	8,  // 11: neomsg.v1.Envelope.read_receipt:type_name -> neomsg.v1.ReadReceiptEvent
	10, // 12: neomsg.v1.Envelope.typing_event:type_name -> neomsg.v1.TypingEvent
	12, // 13: neomsg.v1.Envelope.pong:type_name -> neomsg.v1.PongResponse
	14, // 14: neomsg.v1.Envelope.updates:type_name -> neomsg.v1.UpdatesEvent
	17, // 15: neomsg.v1.Envelope.upload_part_ack:type_name -> neomsg.v1.UploadPartResponse
	21, // 16: neomsg.v1.Envelope.message_ack:type_name -> neomsg.v1.MessageAck
	22, // 17: neomsg.v1.Envelope.sync_response:type_name -> neomsg.v1.SyncResponse
	18, // 18: neomsg.v1.Envelope.error:type_name -> neomsg.v1.ErrorResponse
	0,  // 19: neomsg.v1.SendMessageRequest.msg_type:type_name -> neomsg.v1.MessageType
	6,  // 20: neomsg.v1.SendMessageRequest.media:type_name -> neomsg.v1.MediaRef
	0,  // 21: neomsg.v1.NewMessageEvent.msg_type:type_name -> neomsg.v1.MessageType
	6,  // 22: neomsg.v1.NewMessageEvent.media:type_name -> neomsg.v1.MediaRef
	15, // 23: neomsg.v1.UpdatesEvent.updates:type_name -> neomsg.v1.Update
	5,  // 24: neomsg.v1.Update.new_message:type_name -> neomsg.v1.NewMessageEvent
	8,  // 25: neomsg.v1.Update.read_receipt:type_name -> neomsg.v1.ReadReceiptEvent
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_neomsg_v1_envelope_proto_init() }
func file_neomsg_v1_envelope_proto_init() {
	if File_neomsg_v1_envelope_proto != nil {
		return
	}
	file_neomsg_v1_wire_proto_init()
	file_neomsg_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_AuthRequest)(nil),
		(*Envelope_SendMessage)(nil),
		(*Envelope_AckRead)(nil),
		(*Envelope_Typing)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_GetDifference)(nil),
		(*Envelope_UploadPart)(nil),
		(*Envelope_WireMessage)(nil),
		(*Envelope_SyncRequest)(nil),
		(*Envelope_AuthResponse)(nil),
		(*Envelope_NewMessage)(nil),
		(*Envelope_ReadReceipt)(nil),
		(*Envelope_TypingEvent)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Updates)(nil),
		(*Envelope_UploadPartAck)(nil),
		(*Envelope_MessageAck)(nil),
		(*Envelope_SyncResponse)(nil),
		(*Envelope_Error)(nil),
	}
	file_neomsg_v1_envelope_proto_msgTypes[14].OneofWrappers = []any{
		(*Update_NewMessage)(nil),
		(*Update_ReadReceipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neomsg_v1_envelope_proto_rawDesc), len(file_neomsg_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neomsg_v1_envelope_proto_goTypes,
		DependencyIndexes: file_neomsg_v1_envelope_proto_depIdxs,
		EnumInfos:         file_neomsg_v1_envelope_proto_enumTypes,
		MessageInfos:      file_neomsg_v1_envelope_proto_msgTypes,
	}.Build()
	File_neomsg_v1_envelope_proto = out.File
	file_neomsg_v1_envelope_proto_goTypes = nil
	file_neomsg_v1_envelope_proto_depIdxs = nil
}
