// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: neomsg/v1/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialogType int32

const (
	DialogType_DIALOG_TYPE_UNSPECIFIED DialogType = 0
	DialogType_DIALOG_TYPE_PRIVATE     DialogType = 1
	DialogType_DIALOG_TYPE_GROUP       DialogType = 2
	DialogType_DIALOG_TYPE_SUPERGROUP  DialogType = 3
	DialogType_DIALOG_TYPE_CHANNEL     DialogType = 4
	DialogType_DIALOG_TYPE_SECRET      DialogType = 5
)

// Enum value maps for DialogType.
var (
	DialogType_name = map[int32]string{
		0: "DIALOG_TYPE_UNSPECIFIED",
		1: "DIALOG_TYPE_PRIVATE",
		2: "DIALOG_TYPE_GROUP",
		3: "DIALOG_TYPE_SUPERGROUP",
		4: "DIALOG_TYPE_CHANNEL",
		5: "DIALOG_TYPE_SECRET",
	}
	DialogType_value = map[string]int32{
		"DIALOG_TYPE_UNSPECIFIED": 0,
		"DIALOG_TYPE_PRIVATE":     1,
		"DIALOG_TYPE_GROUP":       2,
		"DIALOG_TYPE_SUPERGROUP":  3,
		"DIALOG_TYPE_CHANNEL":     4,
		"DIALOG_TYPE_SECRET":      5,
	}
)

func (x DialogType) Enum() *DialogType {
	p := new(DialogType)
	*p = x
	return p
}

func (x DialogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialogType) Descriptor() protoreflect.EnumDescriptor {
	return file_neomsg_v1_messages_proto_enumTypes[0].Descriptor()
}

func (DialogType) Type() protoreflect.EnumType {
	return &file_neomsg_v1_messages_proto_enumTypes[0]
}

func (x DialogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialogType.Descriptor instead.
func (DialogType) EnumDescriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	IsBot         bool                   `protobuf:"varint,6,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	LastSeen      int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *User) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type Dialog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          DialogType             `protobuf:"varint,2,opt,name=type,proto3,enum=neomsg.v1.DialogType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	LastMsgId     int64                  `protobuf:"varint,5,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	LastPreview   string                 `protobuf:"bytes,6,opt,name=last_preview,json=lastPreview,proto3" json:"last_preview,omitempty"`
	LastMsgTime   int64                  `protobuf:"varint,7,opt,name=last_msg_time,json=lastMsgTime,proto3" json:"last_msg_time,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,8,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsPinned      bool                   `protobuf:"varint,9,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsMuted       bool                   `protobuf:"varint,10,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsSecret      bool                   `protobuf:"varint,11,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"` // Secret Chat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dialog) Reset() {
	*x = Dialog{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dialog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialog) ProtoMessage() {}

func (x *Dialog) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialog.ProtoReflect.Descriptor instead.
func (*Dialog) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Dialog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dialog) GetType() DialogType {
	if x != nil {
		return x.Type
	}
	return DialogType_DIALOG_TYPE_UNSPECIFIED
}

func (x *Dialog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Dialog) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Dialog) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *Dialog) GetLastPreview() string {
	if x != nil {
		return x.LastPreview
	}
	return ""
}

func (x *Dialog) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

func (x *Dialog) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Dialog) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Dialog) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *Dialog) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	LastActive    int64                  `protobuf:"varint,5,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,6,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *Device) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

// Bot API
type BotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotInfo) Reset() {
	*x = BotInfo{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotInfo) ProtoMessage() {}

func (x *BotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotInfo.ProtoReflect.Descriptor instead.
func (*BotInfo) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BotInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SendBotMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ParseMode     string                 `protobuf:"bytes,3,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBotMessageRequest) Reset() {
	*x = SendBotMessageRequest{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBotMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotMessageRequest) ProtoMessage() {}

func (x *SendBotMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotMessageRequest.ProtoReflect.Descriptor instead.
func (*SendBotMessageRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SendBotMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendBotMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendBotMessageRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

// E2EE — Secret Chat 密钥交换
type PreKeyBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentityKey    []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SignedPreKey   []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	SignedPreKeyId int32                  `protobuf:"varint,4,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	PreKeys        []*PreKey              `protobuf:"bytes,6,rep,name=pre_keys,json=preKeys,proto3" json:"pre_keys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PreKeyBundle) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PreKeyBundle) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PreKeyBundle) GetPreKeys() []*PreKey {
	if x != nil {
		return x.PreKeys
	}
	return nil
}

type PreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         int32                  `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreKey) Reset() {
	*x = PreKey{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKey) ProtoMessage() {}

func (x *PreKey) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKey.ProtoReflect.Descriptor instead.
func (*PreKey) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *PreKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *PreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type EncryptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int32                  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 1=PreKeyWhisper, 3=Whisper
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_neomsg_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *EncryptedMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EncryptedMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_neomsg_v1_messages_proto protoreflect.FileDescriptor

const file_neomsg_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18neomsg/v1/messages.proto\x12\tneomsg.v1\"\xb3\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x15\n" +
	"\x06is_bot\x18\x06 \x01(\bR\x05isBot\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\"\xd7\x02\n" +
	"\x06Dialog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.neomsg.v1.DialogTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1e\n" +
	"\vlast_msg_id\x18\x05 \x01(\x03R\tlastMsgId\x12!\n" +
	"\flast_preview\x18\x06 \x01(\tR\vlastPreview\x12\"\n" +
	"\rlast_msg_time\x18\a \x01(\x03R\vlastMsgTime\x12!\n" +
	"\funread_count\x18\b \x01(\x05R\vunreadCount\x12\x1b\n" +
	"\tis_pinned\x18\t \x01(\bR\bisPinned\x12\x19\n" +
	"\bis_muted\x18\n" +
	" \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_secret\x18\v \x01(\bR\bisSecret\"\xb8\x01\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1f\n" +
	"\vlast_active\x18\x05 \x01(\x03R\n" +
	"lastActive\x12\x1d\n" +
	"\n" +
	"is_current\x18\x06 \x01(\bR\tisCurrent\"_\n" +
	"\aBotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"c\n" +
	"\x15SendBotMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x03 \x01(\tR\tparseMode\"\xe7\x01\n" +
	"\fPreKeyBundle\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x03 \x01(\fR\fsignedPreKey\x12)\n" +
	"\x11signed_pre_key_id\x18\x04 \x01(\x05R\x0esignedPreKeyId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12,\n" +
	"\bpre_keys\x18\x06 \x03(\v2\x11.neomsg.v1.PreKeyR\apreKeys\">\n" +
	"\x06PreKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\x05R\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"A\n" +
	"\x10EncryptedMessage\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\x05R\amsgType\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body*\xa6\x01\n" +
	"\n" +
	"DialogType\x12\x1b\n" +
	"\x17DIALOG_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DIALOG_TYPE_PRIVATE\x10\x01\x12\x15\n" +
	"\x11DIALOG_TYPE_GROUP\x10\x02\x12\x1a\n" +
	"\x16DIALOG_TYPE_SUPERGROUP\x10\x03\x12\x17\n" +
	"\x13DIALOG_TYPE_CHANNEL\x10\x04\x12\x16\n" +
	"\x12DIALOG_TYPE_SECRET\x10\x05B:Z8github.com/neomsg/neomsg/backend/internal/protocol/pb;pbb\x06proto3"

var (
	file_neomsg_v1_messages_proto_rawDescOnce sync.Once
	file_neomsg_v1_messages_proto_rawDescData []byte
)

func file_neomsg_v1_messages_proto_rawDescGZIP() []byte {
	file_neomsg_v1_messages_proto_rawDescOnce.Do(func() {
		file_neomsg_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neomsg_v1_messages_proto_rawDesc), len(file_neomsg_v1_messages_proto_rawDesc)))
	})
	return file_neomsg_v1_messages_proto_rawDescData
}

var file_neomsg_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neomsg_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_neomsg_v1_messages_proto_goTypes = []any{
	(DialogType)(0),               // 0: neomsg.v1.DialogType
	(*User)(nil),                  // 1: neomsg.v1.User
	(*Dialog)(nil),                // 2: neomsg.v1.Dialog
	(*Device)(nil),                // 3: neomsg.v1.Device
	(*BotInfo)(nil),               // 4: neomsg.v1.BotInfo
	(*SendBotMessageRequest)(nil), // 5: neomsg.v1.SendBotMessageRequest
	(*PreKeyBundle)(nil),          // 6: neomsg.v1.PreKeyBundle
	(*PreKey)(nil),                // 7: neomsg.v1.PreKey
	(*EncryptedMessage)(nil),      // 8: neomsg.v1.EncryptedMessage
}
var file_neomsg_v1_messages_proto_depIdxs = []int32{
	0, // 0: neomsg.v1.Dialog.type:type_name -> neomsg.v1.DialogType
	7, // 1: neomsg.v1.PreKeyBundle.pre_keys:type_name -> neomsg.v1.PreKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_neomsg_v1_messages_proto_init() }
func file_neomsg_v1_messages_proto_init() {
	if File_neomsg_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neomsg_v1_messages_proto_rawDesc), len(file_neomsg_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neomsg_v1_messages_proto_goTypes,
		DependencyIndexes: file_neomsg_v1_messages_proto_depIdxs,
		EnumInfos:         file_neomsg_v1_messages_proto_enumTypes,
		MessageInfos:      file_neomsg_v1_messages_proto_msgTypes,
	}.Build()
	File_neomsg_v1_messages_proto = out.File
	file_neomsg_v1_messages_proto_goTypes = nil
	file_neomsg_v1_messages_proto_depIdxs = nil
}
