// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: neomsg/v1/wire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 核心消息体 — 长连接主载荷
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // 雪花 ID
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // 会话 ID（dialog_id）
	FromId        int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int64                  `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MsgType       int32                  `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`   // 0=text, 1=image, 2=voice, 3=file...
	MediaKey      []byte                 `protobuf:"bytes,7,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"` // 媒体文件密钥（小文件可直接带）
	SeqId         int64                  `protobuf:"varint,8,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`         // 用于同步
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsSecret      bool                   `protobuf:"varint,10,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"` // 是否 Secret Chat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_neomsg_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *Message) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Message) GetMediaKey() []byte {
	if x != nil {
		return x.MediaKey
	}
	return nil
}

func (x *Message) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SeqId         int64                  `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_neomsg_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *MessageAck) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageAck) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *MessageAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastSeq       int64                  `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	ChatId        int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // 0 表示全量同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_neomsg_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncRequest) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SyncRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	LastSeq       int64                  `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_neomsg_v1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResponse) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 统一线协议包装（[4B 长度][WirePacket]）
type WirePacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WirePacket_Message
	//	*WirePacket_MessageAck
	//	*WirePacket_SyncRequest
	//	*WirePacket_SyncResponse
	Payload       isWirePacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WirePacket) Reset() {
	*x = WirePacket{}
	mi := &file_neomsg_v1_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirePacket) ProtoMessage() {}

func (x *WirePacket) ProtoReflect() protoreflect.Message {
	mi := &file_neomsg_v1_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirePacket.ProtoReflect.Descriptor instead.
func (*WirePacket) Descriptor() ([]byte, []int) {
	return file_neomsg_v1_wire_proto_rawDescGZIP(), []int{4}
}

func (x *WirePacket) GetPayload() isWirePacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WirePacket) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*WirePacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *WirePacket) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*WirePacket_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *WirePacket) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*WirePacket_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *WirePacket) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*WirePacket_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

type isWirePacket_Payload interface {
	isWirePacket_Payload()
}

type WirePacket_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type WirePacket_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,2,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type WirePacket_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,3,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type WirePacket_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,4,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

func (*WirePacket_Message) isWirePacket_Payload() {}

func (*WirePacket_MessageAck) isWirePacket_Payload() {}

func (*WirePacket_SyncRequest) isWirePacket_Payload() {}

func (*WirePacket_SyncResponse) isWirePacket_Payload() {}

var File_neomsg_v1_wire_proto protoreflect.FileDescriptor

const file_neomsg_v1_wire_proto_rawDesc = "" +
	"\n" +
	"\x14neomsg/v1/wire.proto\x12\tneomsg.v1\"\x84\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x04 \x01(\x03R\x04toId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\x05R\amsgType\x12\x1b\n" +
	"\tmedia_key\x18\a \x01(\fR\bmediaKey\x12\x15\n" +
	"\x06seq_id\x18\b \x01(\x03R\x05seqId\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tis_secret\x18\n" +
	" \x01(\bR\bisSecret\"T\n" +
	"\n" +
	"MessageAck\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x03R\x05seqId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"Z\n" +
	"\vSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\"t\n" +
	"\fSyncResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.neomsg.v1.MessageR\bmessages\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xfe\x01\n" +
	"\n" +
	"WirePacket\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x12.neomsg.v1.MessageH\x00R\amessage\x128\n" +
	"\vmessage_ack\x18\x02 \x01(\v2\x15.neomsg.v1.MessageAckH\x00R\n" +
	"messageAck\x12;\n" +
	"\fsync_request\x18\x03 \x01(\v2\x16.neomsg.v1.SyncRequestH\x00R\vsyncRequest\x12>\n" +
	"\rsync_response\x18\x04 \x01(\v2\x17.neomsg.v1.SyncResponseH\x00R\fsyncResponseB\t\n" +
	"\apayloadB:Z8github.com/neomsg/neomsg/backend/internal/protocol/pb;pbb\x06proto3"

var (
	file_neomsg_v1_wire_proto_rawDescOnce sync.Once
	file_neomsg_v1_wire_proto_rawDescData []byte
)

func file_neomsg_v1_wire_proto_rawDescGZIP() []byte {
	file_neomsg_v1_wire_proto_rawDescOnce.Do(func() {
		file_neomsg_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neomsg_v1_wire_proto_rawDesc), len(file_neomsg_v1_wire_proto_rawDesc)))
	})
	return file_neomsg_v1_wire_proto_rawDescData
}

var file_neomsg_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_neomsg_v1_wire_proto_goTypes = []any{
	(*Message)(nil),      // 0: neomsg.v1.Message
	(*MessageAck)(nil),   // 1: neomsg.v1.MessageAck
	(*SyncRequest)(nil),  // 2: neomsg.v1.SyncRequest
	(*SyncResponse)(nil), // 3: neomsg.v1.SyncResponse
	(*WirePacket)(nil),   // 4: neomsg.v1.WirePacket
}
var file_neomsg_v1_wire_proto_depIdxs = []int32{
	0, // 0: neomsg.v1.SyncResponse.messages:type_name -> neomsg.v1.Message
	0, // 1: neomsg.v1.WirePacket.message:type_name -> neomsg.v1.Message
	1, // 2: neomsg.v1.WirePacket.message_ack:type_name -> neomsg.v1.MessageAck
	2, // 3: neomsg.v1.WirePacket.sync_request:type_name -> neomsg.v1.SyncRequest
	3, // 4: neomsg.v1.WirePacket.sync_response:type_name -> neomsg.v1.SyncResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_neomsg_v1_wire_proto_init() }
func file_neomsg_v1_wire_proto_init() {
	if File_neomsg_v1_wire_proto != nil {
		return
	}
	file_neomsg_v1_wire_proto_msgTypes[4].OneofWrappers = []any{
		(*WirePacket_Message)(nil),
		(*WirePacket_MessageAck)(nil),
		(*WirePacket_SyncRequest)(nil),
		(*WirePacket_SyncResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neomsg_v1_wire_proto_rawDesc), len(file_neomsg_v1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neomsg_v1_wire_proto_goTypes,
		DependencyIndexes: file_neomsg_v1_wire_proto_depIdxs,
		MessageInfos:      file_neomsg_v1_wire_proto_msgTypes,
	}.Build()
	File_neomsg_v1_wire_proto = out.File
	file_neomsg_v1_wire_proto_goTypes = nil
	file_neomsg_v1_wire_proto_depIdxs = nil
}
