-- AlterTable
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'file';
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "mime" TEXT;
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "diskPath" TEXT;
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "publicPath" TEXT;
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "durationMs" INTEGER;
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "posterMediaId" TEXT;
ALTER TABLE "MediaFile" ADD COLUMN IF NOT EXISTS "sha256" TEXT;

CREATE INDEX IF NOT EXISTS "MediaFile_kind_createdAt_idx" ON "MediaFile"("kind", "createdAt");
